### PR TITLE
barbican: Enable SSL testing

### PR DESCRIPTION
**Pull request by cmurphy**
Depends on https://github.com/crowbar/crowbar-openstack/pull/858

### CODE REVIEW

**Comment by sayalilunkad** [comment]
Can you please update the commit message to prefix it with Barbican:. We normally follow that for all commit messages.

**Comment by sayalilunkad** [comment]
Can you rebase, this https://github.com/SUSE-Cloud/automation/pull/1731 was merged so we can get rid of the travis failure

**Comment by cmurphy** [comment]
@sayalilunkad I can, but I expect the mkcloud test will still fail until https://github.com/crowbar/crowbar-openstack/pull/858 is merged, no?

**Comment by sayalilunkad** [comment]
@cmurphy no we need this to test the other PR. I guess it will just ignore it for now.

**Comment by cmurphy** [comment]
The mkcloud test seems to be failing because it couldn't find the bind package. I don't think that's related to this patch but I also don't see other PRs with the same issue, maybe the repo had a hiccup?

**Comment by sayalilunkad** [comment]
[(3) S56P8 Add SSL support to barbican barclamp](https://trello.com/c/ibqvVB1Y/474-3-s56p8-add-ssl-support-to-barbican-barclamp)

**Pull request merged**
