### PR TITLE
trackupstream: Track openstack-horizon-plugin-sahara-ui and openstack-horizon-plugin-trove-ui

### PR DESCRIPTION
**Pull request by sidthe**

### CODE REVIEW

**Comment by sidthe** [comment]
@toabctl not sure if I did the right thing in terms of how I handled the PR

**Comment by toabctl** [comment]
> @toabctl not sure if I did the right thing in terms of how I handled the PR

@sidthe can you just squash the commit? Doesn't matter for me if my commit is lost.

**Comment by sidthe** [comment]
@toabctl thanks Tom, is that better?

**Comment by sidthe** [comment]
@toabctl thanks! what's the process for the automation repo? does it need a second reviewer as well to be merged?

**Pull request merged**
