### PR TITLE
Add better debugging output

### PR DESCRIPTION
**Pull request by nicolasbock**
This patch adds line number and function information to the debug output of
mkcloud and qa_crowbarsetup.sh (controlled by debug_mkcloud and
debug_qa_crowbarsetup).

### CODE REVIEW

**Comment by aplanas** [comment]
+1 thanks!!

**Comment by nicolasbock** [comment]
Output sample:
~~~
+(mkcloud:1469) main(): usage
+(mkcloud:1105) usage(): show_steps
+(mkcloud:1041) show_steps(): cat
++(mkcloud:1041) show_steps(): expand_steps all
++(mkcloud:1402) expand_steps(): local runcmds=
++(mkcloud:1403) expand_steps(): local localwantedcmds=all
~~~

**Comment by toabctl** [comment]
+1

**Comment by aspiers** [comment]
+100

**Pull request merged**
