### PR TITLE
syncSLErepos fixes for clouddata.cloud.suse.de

### PR DESCRIPTION
**Pull request by dirkmueller**
clouddata.cloud.suse.de was serving incorrect data. enough updates to make it work again..

### CODE REVIEW

**Comment by aspiers** [comment]
Why pushed directly to `master` instead of merging?

**Comment by dirkmueller** [comment]
@aspiers it was a mistake (wrong remote used)

**Comment by aspiers** [comment]
@dirkmueller No worries ;-) Easy mistake to make.  We could opt to disallow pushing to `master` for everyone, what do you think?

**Comment by aspiers** [comment]
And BTW this is quite a cool approach to managing repo settings: https://probot.github.io/apps/settings/

**Pull request closed without merging**
