### PR TITLE
add cloudsource=Mx support back for cloud 9 milestones

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by gosipyan** [comment]
Testing with https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-scenario-1a/1051/console

**Comment by gosipyan** [comment]
Please rebase to current master its missing fix for nfs share folder creation 
"Error (35): We do not have cloud install media in /srv/tftpboot/suse-12.4/x86_64/repos/Cloud - giving up"

**Comment by dirkmueller** [comment]
rebased and restarted as https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-scenario-1a/1052/console

**Comment by gosipyan** [comment]
@dirkmueller thanks!

**Comment by dirkmueller** [comment]
https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-scenario-1a/1053/console is the 3rd try, and thats gonna be a charm, hopefully

**Comment by dirkmueller** [comment]
once more..

**Pull request merged**
