### PR TITLE
Partly revert move to crowbarctl

### PR DESCRIPTION
**Pull request by rsalevsky**
The crowbarctl proposal * commands are broken by design.

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
https://ci.suse.de/job/openstack-mkcloud/26823 is an example. not even the error / stacktrace appears anymore. just the timeout

**Comment by MaximilianMeister** [comment]
i guess reverting makes sense for now +1

**Comment by toabctl** [comment]
> The crowbarctl proposal * commands are broken by design.

Out of interest - are there bugs for the issues so we can track progress on the problems?

**Comment by vuntz** [comment]
+1

**Comment by jdsn** [comment]
:+1: (please create a card to fix this issue in crowbarctl)

**Pull request merged**
