### PR TITLE
Add option to enable proposal debug setting

### PR DESCRIPTION
**Pull request by dirkmueller**
now a want_all_debug=1 should end up in a deployment with
debug enabled.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by bmwiedemann** [comment]
putting it in that list, means we only enable debug on barclamps that have an ssl option. but if that is sufficient for you, I give it a +1

**Comment by dirkmueller** [comment]
@bmwiedemann changed

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
