### PR TITLE
Readd a daily run of the cleanvm matrix

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
@dirkmueller shouldn't that be triggered *after* the trackupstream job is done?

**Comment by rhafer** [comment]
+1

**Comment by rhafer** [comment]
> shouldn't that be triggered after the trackupstream job is done? And I guess some time is needed so the package builds are done triggered by trackupstream

Hm, true. It seem in the past (before the jbb switch) we ran it a 4am daily (https://github.com/SUSE-Cloud/automation/commit/552a88954e74fc957725a4d6a458dce1eb2c6249#diff-54668dddec90538b7be71f34abba3096L90). Not sure if that is enough time to rebuild everything, trackupstream runs a 1am IIRC.

**Comment by dirkmueller** [comment]
@rhafer @toabctl I don't think that makes any difference, since it is very unlikely that OBS would have finished building the repositories + publishing within 3 hours. But I've restored the 4am time slot now to make it more predictable when it happens.

**Comment by toabctl** [comment]
+1

**Comment by rhafer** [comment]
+1

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
