### PR TITLE
Scenario fixes

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by abel-navarro** [comment]
+1

**Comment by bmwiedemann** [comment]
first commit message could give a hint, why to "not assign swift-proxy-ceilometer-middleware"

**Comment by dirkmueller** [comment]
@bmwiedemann updated

**Comment by vmoravec** [comment]
+1

**Comment by vmoravec** [comment]
Our docs are showing ceilometer-swift-proxy-middleware deployed on a cluster:
http://docserv.nue.suse.com/documents/Cloud6/suse-openstack-cloud-deployment/single-html/images/depl_barclamp_ceilometer_deployment.png

**Comment by dirkmueller** [comment]
@vmoravec ok, lets retry without that change for now, no harm done. dropped

**Pull request merged**
