### PR TITLE
use the meta package instead of the pattern

### PR DESCRIPTION
**Pull request by MaximilianMeister**
the cloud_admin pattern is not in the SLE12 Cloud repo

### CODE REVIEW

**Comment by vuntz** [comment]
Well, we could just always use the package (unless it didn't exist in Cloud 4, but I think it did?).

There might be other references (in the backup / restore code, for instance).

**Comment by MaximilianMeister** [comment]
> Well, we could just always use the package (unless it didn't exist in Cloud 4, but I think it did?).

@vuntz i cant find this package in D:C:4

**Comment by dirkmueller** [comment]
or we could add the pattern.. afaik its not possible to have an addon product installing a package directly, we need to add the pattern dependency there.

**Comment by dirkmueller** [comment]
I've added the pattern back to the media in staging.. so this change shouldn't be necessary anymore.

**Comment by MaximilianMeister** [comment]
@dirkmueller thanks. i will close this then

**Pull request closed without merging**
