### PR TITLE
Deploy Magnum with default scenarios

### PR DESCRIPTION
**Pull request by jsuchome**

### CODE REVIEW

**Comment by jdsn** [comment]
:+1: lgtm - can you trigger another CI run which uses such a scenario?

**Comment by dirkmueller** [comment]
I'm not sure that this is going to work - there is no code for uploading the magnum image in those batch files as far as I can see..

**Comment by jsuchome** [comment]
I'm not sure this was correct, let's just close it if we do not need it

**Comment by mjura** [comment]
I haven't tested HA scenario but LGTM

**Pull request closed without merging**
