### PR TITLE
qa_crowbarsetup: Make manila with generic driver work with scenarios

### PR DESCRIPTION
**Pull request by vuntz**
This requires the scenarios to be updated with the right config values
and placeholders.

### CODE REVIEW

**Comment by vuntz** [comment]
https://ci.suse.de/job/openstack-mkcloud/15005/ is the build without batch, and a build with batch https://ci.suse.de/job/openstack-mkcloud/15006/ (manually triggered).

**Comment by bmwiedemann** [comment]
+1 code looks good, though I wonder if we could re-use the mechanism that replaces @@controller@@ with the actual node name.

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
> I wonder if we could re-use the mechanism that replaces @@controller@@ with the actual node name.

So I specifically avoided using `@@` to not create confusion with that mechanism. The `@@` magic is working in crowbar_batch directly (it's expanding aliases); I'm not really sure how that would work for this. Do you have an idea how?

**Pull request merged**
