### PR TITLE
Revert "ardana: Restructure network config"

### PR DESCRIPTION
**Pull request by toabctl**
This reverts commit cc97c4b4b3c43410cb8829406879f95523bb848f.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
I would have liked a bit more context in such commits - e.g. "Why"

**Comment by aspiers** [comment]
That's what I was going to say too.  @toabctl Please don't forget about the rest of the team, thanks ;-)

**Comment by bmwiedemann** [comment]
And there is always this toabctl-2019 guy who might have no clue either why this was done back then and could need some hint.

**Comment by aspiers** [comment]
Exactly, there is also the aspiers-Feb-2018 guy who *definitely* won't remember anything ;-)

**Pull request merged**
