### PR TITLE
Memory

### PR DESCRIPTION
**Pull request by toabctl**

### CODE REVIEW

**Comment by aplanas** [comment]
LGTM: +1

**Comment by vuntz** [comment]
+1

**Comment by bmwiedemann** [comment]
I'd prefer to make the service VM use less RAM.

**Comment by toabctl** [comment]
So I did a "free -s 1" run during a tempest smoketest run on the only compute node (with 2 GB memory) in a 2 node cluster. The lowest free memory value I reached was **65096K** . And all tests passed.

**Comment by toabctl** [comment]
So another thing I recognize in the same setup:

1) I boot the manila-service instance with the flavor with 256 MB RAM. Works. But when I reboot the node (```nova reboot --hard ID```) and look at the console-log, I get:
```
Boot logging started on /dev/tty1(/dev/console) at Wed Feb 10 18:52:30 2016
FATAL: Error inserting cirrus (/lib/modules/3.0.101-0.47.71-default/kernel/drivers/gpu/drm/cirrus/cirrus.ko): Invalid argument
Waiting for device /dev/vda1 to appear: .....................
```

And the boot doesn't continue (and it's not about missing virtio-blk in the initrd).
Doing the same with a different flavor (now 512 MB RAM) but using the same image, a reboot (same command) just works. So memory makes a difference here.
Now you can argue that we should minimize the footprint of the image and I agree. But I also want to have a image build by OBS (I started that already, see https://build.suse.de/package/show/home:tbechtold:Images/manila-service-image ) and not something handmade. But the image from IBS doesn't even boot with 256 MB currently.

**Comment by vuntz** [comment]
@bmwiedemann @jdsn do you have any other solution that can be implemented in the next day or so? If not, we should merge that -- we really could do with less red in gating / jenkins...

**Comment by dirkmueller** [comment]
+1

**Comment by jdsn** [comment]
@vuntz I am fine to merge it as a quick workaround, we just need to be aware of the consequences.

**Pull request merged**
