### PR TITLE
qa_crowbarsetup: rewrite onadmin_get_ip_from_dhcp in perl or ruby

### PR DESCRIPTION
**Pull request by bmwiedemann**
we now have roundup tests covering this function

### CODE REVIEW

**Comment by toabctl** [comment]
Hm. According to our cloud-dev-language-strategy Python or Ruby should be used...

**Comment by jdsn** [comment]
If it was a python tool then maybe, but this is a shell script so use default linux tools:
awk '/^lease /{ip=$2} /ethernet/{if ($3=="52:54:07:77:77:07;")res=ip } END{print res}' /var/lib/dhcp/db/dhcpd.leases

**Comment by jdsn** [comment]
Or use instead: https://github.com/SUSE-Cloud/automation/pull/217

**Comment by bmwiedemann** [comment]
closing in favour of #217

**Pull request closed without merging**
