### PR TITLE
qa_crowbarsetup: handle dropped bc- prefix differently

### PR DESCRIPTION
**Pull request by bmwiedemann**

### CODE REVIEW

**Comment by vmoravec** [comment]
I  just think that it might be confusing to have a single json file for different cloud versions. It's impossible to guess which cloud version the file belongs if looking at it.

**Comment by bmwiedemann** [comment]
I think, it would be more confusing to have multiple json files for one cloud hardware/network - so you would edit one and your changes would not be used, because the other file is used

**Comment by bmwiedemann** [comment]
proposed https://github.com/crowbar/crowbar/pull/2161

**Comment by bmwiedemann** [comment]
gating failed in an unrelated eary place - maybe addressed by https://github.com/crowbar/crowbar-core/pull/65

**Comment by jdsn** [comment]
PR https://github.com/crowbar/crowbar/pull/2161 got merged.
So :+1:

**Comment by vuntz** [comment]
Not a huge fan of the hack in the other PR (even if I gave +1), but why not. +1.

**Pull request merged**
