### PR TITLE
Ardana qe tests nova

### PR DESCRIPTION
**Pull request by jennywei8**
Please review the changes for nova and ceilometer

### CODE REVIEW

**Comment by jennywei8** [comment]
Add subunit protocal

**Comment by flaviodsr** [comment]
Running those tests fails when trying to send the subunit results to OS-Health, see: http://10.84.144.253:8080/job/ci-ardana-qe-tests/83/console

Also, there are some tests failing, are they expected to fail? Is it possible to have a filter containing only tests that are expected to pass?

**Comment by jennywei8** [comment]
Add condition on the checkpoint in source code, once the change is merged into ardana-qe repo, the subunit test result should pass.

**Comment by agreentree** [comment]
looks good to me for subunit and rocketchat output

**Pull request merged**
