### PR TITLE
Convert qa tests trigger and jobs for tempest and cct to jjb

### PR DESCRIPTION
**Pull request by vmoravec**
The jobs were already in use for some time, this PR converts them into JJB

### CODE REVIEW

**Comment by kbaikov** [comment]
+1 assuming this works and was used to recreate the jobs.

**Comment by aplanas** [comment]
I can test it, but LGTM

**Comment by vmoravec** [comment]
@kbaikov @aplanas The jobs on ci.suse.de are already updated from these files and I built clouds already on qa2 with them.

**Comment by aplanas** [comment]
@vmoravec good to merge, then.

**Pull request merged**
