### PR TITLE
trackupstream: Also track the Mitaka packages

### PR DESCRIPTION
**Pull request by toabctl**

### CODE REVIEW

**Comment by dirkmueller** [comment]
okayish, but so far we didn't want to "branch" yet. when is a good time?

**Comment by toabctl** [comment]
> okayish, but so far we didn't want to "branch" yet. when is a good time?

When a) the packages are fine (so we don't have to duplicate the work for Mitaka and Master) and b) stable tarballs from stable branches are available (already the case for some components)

**Comment by toabctl** [comment]
@dirkmueller I created the branches. So now is a good time to track mitaka.

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
