### PR TITLE
Disable trackupstream for master for now since we are focusing on

### PR DESCRIPTION
**Pull request by dirkmueller**
Liberty

Keeping this disabled for the next month or so will help us
on focusing on getting the Liberty release out.

### CODE REVIEW

**Comment by aplanas** [comment]
Makes sense for me: +1

**Comment by toabctl** [comment]
+1

**Comment by bmwiedemann** [comment]
On the other hand I'm a bit worried that this will make it harder to get Master back to green later... and increase the disconnect towards upstream. e.g. we would not have discovered https://bugs.launchpad.net/bugs/1520096

**Comment by aplanas** [comment]
@bmwiedemann but is only during a month, even if the PR is not merged, not many people will be tracking the status when we are prioritizing other tasks

**Comment by toabctl** [comment]
@bmwiedemann and Master is broken anyway. Maybe the packages build but cleanvm is red since weeks.

**Pull request merged**
