### PR TITLE
increase the timeout for crowbar_batch command

### PR DESCRIPTION
**Pull request by jsuchome**
I've seen it fail in recent builds at ceilometer step...

### CODE REVIEW

**Comment by jdsn** [comment]
:+1: lgtm and should not hurt

**Comment by aspiers** [comment]
I disagree that this will not hurt - it simply attempts to sweep [the underlying issue](https://bugzilla.suse.com/show_bug.cgi?id=935462) under the carpet and will also introduce extra delay to Jenkins jobs experiencing this type of issue, which causes the mkcloud resources to be held for longer.  Maybe it's a reasonable approach in the short term bearing in mind that we have many Jenkins issues to deal with currently, but in general we should try hard to avoid these ugly bandaids and fix the real problem.

**Comment by jsuchome** [comment]
It did not help my original issue actually, and some better solution to what we have been experiencing might be here: https://github.com/crowbar/crowbar-core/pull/120

**Comment by nkrinner** [comment]
We also need a timeout of at least 1500 for crowbar batch. The default timeout of 500 seconds is simply not enough as deployments cat take up to about 20 minutes even without pacemaker involved.

**Comment by aspiers** [comment]
I agree with increasing the default to 900 or *maybe* 1200.  Anything beyond that sounds to me like a bug.  @nkrinner the timeout is not for the whole deployment but for a single barclamp.  Are you really saying a single proposal can take over 20 minutes to apply?

**Comment by jdsn** [comment]
> Maybe it's a reasonable approach in the short term bearing in mind that we have many Jenkins issues to deal with currently, but in general we should try hard to avoid these ugly bandaids and fix the real problem.

That was exactly what we were discussing in IRC before I merged this PR. It was meant as a quick fix to workaround an issue. Sorry for not mentioning it explicitly. @jsuchome found out later that it did not help.

So should we revert this commit? Or create another PR that sets the timeout to a more sane level? @aspiers @nkrinner ?

**Comment by aspiers** [comment]
I would say revert it.

**Comment by nkrinner** [comment]
If I remember my testing correctly, applying only the ceilometer barclamp took about 17 minutes. Keep in mind that the runlist is huge at this point if it is a single controller node. At the current state a timeout value less than about 1500 will most likely break the gating again.

I agree it is worth investigating why a ceilometer deployment takes that long. I think many other services are adjusted or restarted during the deployment, but I did not look at that into too much detail. It did not look broken to me at that time.

**Comment by aspiers** [comment]
If it takes that long, IMHO that is broken even if it finishes successfully - I can't think of any good reason why any of the setup we do would need that much time.  So yes we definitely need to examine this in more detail.  Simply increasing the timeout is the lazy option and will not help our customers.

**Comment by nkrinner** [comment]
It took 15 minutes on the controller node only for the ceilometer deployment in my last test.

**Comment by aspiers** [comment]
@nkrinner Please can you provide profiling details?  Is this just ceilometer which is slow?

**Comment by nkrinner** [comment]
@aspiers I put the log from the ceilometer deployment on the controller node here: https://w3.suse.de/~nkrinner/controller-ceilometer-deployment.log
It seems that we need three chef runs for the deployment. I don't remember the other barclamps needing that long.

**Comment by nkrinner** [comment]
The controller node holds three roles and each one is applied in a chef run. The run list is quite long at that point, so each run takes about five minutes.

**Comment by aspiers** [comment]
@nkrinner What three roles are you talking about?  The run list is identical for each of these three chef runs.

**Comment by nkrinner** [comment]
There are three different ceilometer roles.  ceilometer-cagent, ceilometer-server and ceilometer-swift-proxy-middleware.  The runlist should also be a bit different each time.

**Pull request merged**
