### PR TITLE
jenkins/mkcloud6-upgrade: upgrade to cloud6

### PR DESCRIPTION
**Pull request by bmwiedemann**

### CODE REVIEW

**Comment by jdsn** [comment]
:+1:

**Comment by bmwiedemann** [comment]
real test of this change is running in https://ci.suse.de/job/openstack-mkcloud/17898/

**Comment by vmoravec** [comment]
+1

**Comment by vuntz** [comment]
https://ci.suse.de/job/openstack-mkcloud/17898/consoleFull looks quite promising, actually! The issue there seems to be unrelated to upgrade.

**Pull request merged**
