### PR TITLE
Multi arch

### PR DESCRIPTION
**Pull request by nkrinner**
Support for multiple architectures

### CODE REVIEW

**Comment by vuntz** [comment]
+1, tested with https://github.com/crowbar/crowbar/pull/2167 and https://github.com/crowbar/crowbar-core/pull/83

**Comment by nkrinner** [comment]
Gating will fail without https://github.com/crowbar/crowbar/pull/2167 and https://github.com/crowbar/crowbar-core/pull/85

**Comment by nkrinner** [comment]
Rebased

**Comment by abel-navarro** [comment]
LGTM: +1

**Comment by vuntz** [comment]
I've rebased this on top of https://github.com/SUSE-Cloud/automation/pull/633 at https://github.com/vuntz/automation/compare/repos-yml...vuntz:multi-arch-yaml?expand=1

**Comment by vuntz** [comment]
@nkrinner can you rebase? Or maybe just take the commits from my branch (see previous comment)

**Comment by nkrinner** [comment]
Rebased

**Comment by nkrinner** [comment]
And again rebased

**Comment by vuntz** [comment]
> And again rebased

You need https://github.com/nkrinner/automation/pull/3

**Comment by vuntz** [comment]
+1, but we probably don't want the merge commit in the history.

**Comment by nkrinner** [comment]
@vuntz Agreed, removed the merge commit from the history

**Comment by jsuchome** [comment]
+1, tested with crowbar/crowbar#2167 and crowbar/crowbar-core#83

**Pull request merged**
