### PR TITLE
Add more rally tests

### PR DESCRIPTION
**Pull request by gosipyan**

### CODE REVIEW

**Comment by gosipyan** [comment]
Run results : https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-rally-test/

**Comment by aplanas** [comment]
scp: /root/scripts/scenarios/rally/rally-test.json: No such file or directory

**Comment by gosipyan** [comment]
@aplanas For testing I added file manually. Because cloud was deployed with master. After merge and redeploy file should be there.

**Comment by aplanas** [comment]
The output is super cool!
https://ci.suse.de/view/Cloud/view/QA/job/cloud-mkphyscloud-qa-rally-test/116/artifact/.artifacts/output.html

**Pull request merged**
