### PR TITLE
Generate certs for horizon in qa scenarios

### PR DESCRIPTION
**Pull request by vmoravec**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
+1 change seems good

**Comment by jdsn** [comment]
:+1: (assuming that it creates self-signed certificates and does not need any other magic or integration)

**Comment by vmoravec** [comment]
@jdsn The magic was implemented here by dirk: https://github.com/crowbar/crowbar-openstack/pull/157.

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
