### PR TITLE
qa_crowbarsetup: Use m1.tiny when booting testvm instance for docker

### PR DESCRIPTION
**Pull request by vuntz**
It seems that the docker backend doesn't allow disk overcommit.

### CODE REVIEW

**Comment by jsuchome** [comment]
Looks good, running testsetup now...

**Comment by jsuchome** [comment]
So, I failed to execute full testsetup (because I patched wrong qa_crowbarsetup), but I can confirm that `nova boot --image cirros --flavor m1.tiny` actually works while it fails with `--flavor m1.smaller`

**Comment by jsuchome** [comment]
+1

**Comment by kbaikov** [comment]
+1

**Comment by nkrinner** [comment]
+1

**Pull request merged**
