### PR TITLE
Update Rally call using the CLI from upstream

### PR DESCRIPTION
**Pull request by aplanas**
Depends on https://review.openstack.org/#/c/223569/

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by MaximilianMeister** [comment]
needs rebase

**Comment by aplanas** [comment]
* Rebased

**Comment by toabctl** [comment]
Upstream commit not merged yet...

**Comment by aplanas** [comment]
I really think that is safe to merge it, backup server is using my branch so I decoupled upstream from this server.

**Pull request merged**
