### PR TITLE
preparations for crowbar on sle12

### PR DESCRIPTION
**Pull request by MaximilianMeister**
https://trello.com/c/xXhjGZzs/859-3-sle12-prepare-mkcloud-to-start-sle12-for-admin-server

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
> how about taking the chance of doign the proper way of using kpartx -av to read the partition table and then mount partition 1?

https://github.com/SUSE-Cloud/automation/pull/436

**Comment by vuntz** [comment]
Would it make sense to document that this is a temporary option (as this will be always SLE12 in the future)?

**Comment by dirkmueller** [comment]
imho not documenting it is fine until we have switched to SLE12 (which hopefully happens soon..)

+1

**Comment by bmwiedemann** [comment]
:+1:

**Pull request merged**
