### PR TITLE
qa_crowbarsetup: Update use of ceph test suite for SES2

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by MaximilianMeister** [comment]
don't know how the storage team handles their git branches, but will this storage2 branch stay like this? or will it be merged into master at some point?

**Comment by vuntz** [comment]
> don't know how the storage team handles their git branches, but will this storage2 branch stay like this? or will it be merged into master at some point?

I'm not sure; I'll ask.

**Comment by vuntz** [comment]
>> don't know how the storage team handles their git branches, but will this storage2 branch stay like this? or will it be merged into master at some point?
> 
> I'm not sure; I'll ask.

Storage team will keep the storage2 branch, yes.

**Comment by MaximilianMeister** [comment]
can you rebase? then I will merge

**Comment by vuntz** [comment]
@MaximilianMeister owners can merge without a rebase :-)

**Pull request merged**
