### PR TITLE
qa_crowbarsetup: use 9GB flavor

### PR DESCRIPTION
**Pull request by bmwiedemann**
this is a partial revert of commit d52cd69c7

We found that a Hyper-V compute node would refuse
to start an 8GB image in an 8GB flavor
being off by 472 KB - possibly for some metadata

exact error message was:
HyperVException: Cannot resize the image to a size smaller than the VHD max. internal size: 8590417920. Requested disk size: 8589934592

### CODE REVIEW

**Comment by abel-navarro** [comment]
The reason I reduced the flavor size last time was because we observed some errors when spawning instances (*no host found*). This was caused because there was no space in any compute node to actually spawn the VM. The lack of space is due to some _base image_ leftovers on the compute node after deleting an image. If you create/destroy several VMs from different images, that error is more likely to appear.

I'm ok with setting the flavor to 9GB if the CI gives us green light. Otherwise we may want *mkcloud* to create bigger volumes for the compute nodes.

**Comment by jdsn** [comment]
:+1: in general for the simple fix (erm workaround) but this feels to be more hyperv related, as 8GB should be 8GB and hyperv should account for the metadata

I agree with abel that we need to carefully monitor the results of this change though. It might have unwanted side effects as we allocate 1GB for just 472kB.

What about reducing the size of our 8GB image to 7.9GB? That should fit into and 8GB VHD, right? That does not solve the actual problem either but is a workaround with less side effects. Just an idea.

**Comment by bmwiedemann** [comment]
for reference, upstream code that does the size checking (changed in master)
http://git.openstack.org/cgit/openstack/nova/commit/?id=af737b9529ed64eb66560045a36fd82fdce3ac6b

**Comment by mjura** [comment]
LGTM

**Pull request closed without merging**
