### PR TITLE
qa_crowbarsetup.sh: Delet testvm after creation

### PR DESCRIPTION
**Pull request by sayalilunkad**
This deletes testvm after it is created to free compute node resources.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
commit message should answer "Why" - something like "to free compute node memory for ..."

**Comment by sayalilunkad** [comment]
@nicolasbock It is a good practice to clean up the instances created while testing and not doing so in this case is creating problems for the magnum job as magnum tries to create a cluster with 2 master and 1 minion node which fails because of "No host found" due to no space on the disk. I ran the magnum job with this PR https://ci.suse.de/job/openstack-mkcloud/82053/  and it seems to solve the problem with magnum but there is a call to the testvm after the magnum stuff which breaks the gating now.:/

**Comment by nicolasbock** [comment]
@sayalilunkad Thanks, that explains it :smile:

**Comment by dirkmueller** [comment]
@sayalilunkad I found it rather convenient to have a quick way to start a testvm though. I wonder if can get the best of both worlds by doing the magnum cluster tests prior the testvm stuff.

**Comment by sayalilunkad** [comment]
@dirkmueller we could do that but I am not sure that is such a good idea because if something is wrong in nova it will show up as a magnum cluster failure which could be misleading.

**Comment by jdsn** [comment]
@sayalilunkad Is this PR still WIP? Or is it still relevant?
Can we close this PR? If not it at least needs a rebase.

**Comment by sayalilunkad** [comment]
@jdsn yes let's close this, not relevant for SOC 8 at least.

**Pull request closed without merging**
