### PR TITLE
mkcloud: allow to skip supportconfig gathering

### PR DESCRIPTION
**Pull request by bmwiedemann**
when debugging mkcloud, this is one of the annoyingly slow parts
and this can now be avoided

### CODE REVIEW

**Comment by jdsn** [comment]
I'd vote for the switch to be UPPERCASE

**Comment by aspiers** [comment]
Wouldn't it make sense to only collect supportconfig if something went wrong?

**Comment by bmwiedemann** [comment]
It is only collected if something went wrong, because otherwise error_exit is not called.
Maybe we could even reverse the logic to only collect it when running in jenkins, because in other cases you still have the live cloud to look at.

**Comment by aspiers** [comment]
Ah right, thanks.  In this case I think it is good how it is currently - I would prefer that supportconfig gets taken by default.

**Pull request merged**
