### PR TITLE
qa_crowbarsetup: only run on VMs by default

### PR DESCRIPTION
**Pull request by bmwiedemann**
it already happened twice that someone ran the script on the host instead of the admin VM

### CODE REVIEW

**Comment by bmwiedemann** [comment]
successfully tested on virtual and physical

**Comment by mimi1vx** [comment]
:+1:

**Comment by rsalevsky** [comment]
:+1:

**Comment by toabctl** [comment]
I guess this only works in `kvm` VMs, right? Anyway +1

**Comment by bmwiedemann** [comment]
yes, KVM-only, but that is what we do everywhere and you can still override it, if you need to.

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
