### PR TITLE
mkcloud: documentation for lonely nodes and crowbar_register

### PR DESCRIPTION
**Pull request by MaximilianMeister**
* document setuplonelynodes and crowbar_register steps
* clarify the term lonely nodes

### CODE REVIEW

**Comment by aspiers** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by jdsn** [comment]
:-1: I am just preparing a PR that cleans up the entire documentation

**Comment by jdsn** [comment]
https://github.com/SUSE-Cloud/automation/pull/287 will supersede this PR
287 alreay incorporates the changes done in this PR.

**Pull request closed without merging**
