### PR TITLE
new automation tests for cinder, swift and nova

### PR DESCRIPTION
**Pull request by markseger**
copy of tests to run cinder, swift performance and nova attach testing

### CODE REVIEW

**Comment by markseger** [comment]
I'll have to look more closely at cinder-parallel and nova-attach, but 
getput doesn't use subunit

-mark

**Comment by markseger** [comment]
I found what I think is the problem namely that there is a function in cinder_test_funcs.py called error() that isn't calling subunit-output --fail and as a result the subunit log isn't being written correctly when it's called from the automated tests. https://gerrit.suse.provo.cloud//#/c/4649 had been patched to do so and once merged will hopefully resolve the problem with no need to change any of the automated code.

**Comment by markseger** [comment]
ready to merge

**Comment by agreentree** [comment]
mark says no code changes needed at this point, so I will see if I can approve for this to merge

**Comment by flaviodsr** [comment]
Please take a look on the following issues:

Test: cinder
Issue: Error sending subunit output do openstack-health, see: http://10.84.144.253:8080/job/ci-ardana-qe-tests/99/console

Test: cinder-parallel, getput, nova-attach
Issue: The list of failed tests includes tests that passed, see: https://chat.suse.de/channel/cloud-qe-hlm007?msg=JPwS7BatBZ6F4dpyr

Test: getput
Issue: Test results are not clear, it report that all tests passed but the message says that it failed, see: https://chat.suse.de/channel/cloud-qe-hlm007?msg=SvGciPHgEcfXgAFow

**Comment by markseger** [comment]
I think all my scripts are working now. I've made changes to nova-attach, cinder-parallel and getput. Cinder-parallel and nova-attach were verified the other day on hlm007 before ti became unusable. Getput has been tested on hlm202 and I also ran cinder-parallel and nova-attach there as well.

These 3 scripts all work, generate subunit output and update the dashboard correctly. I have not made any changes to cinder-new tests because the required subunit fix was in the shared library used by nova-attach and cinder-parallel and as stated is working correctly. It would be good to test cinder-new tests on hlm202 as well BUT they require the use of openstack commands which are currently not working.

I think it should be ok to merge.

**Comment by markseger** [comment]
need to start over

**Pull request closed without merging**
