### PR TITLE
Start tracking the initial ardana packages

### PR DESCRIPTION
**Pull request by toabctl**
The list of packages is not yet complete because packages are still missing.

### CODE REVIEW

**Comment by nicolasbock** [comment]
Should do you want to add the 'do not merge' label or do you plan on merging this for now and then add the missing packages in a follow-up?

**Comment by toabctl** [comment]
> Should do you want to add the 'do not merge' label or do you plan on merging this for now and then add the missing packages in a follow-up?

I would like to get this merged and add the other packages when available.

**Comment by dirkmueller** [comment]
can we avoid adding every ardana packages to 3 exclude lists all the time?

also, wasn't the plan to create an ardana-openstack package that wraps all the git repos?

**Comment by toabctl** [comment]
> also, wasn't the plan to create an ardana-openstack package that wraps all the git repos?

There was that idea. But Charles did ardana-neutron (and you accepted it) so I would say we go for a package per repo for now. we can create a pattern to be able to install everything with one command...

**Comment by toabctl** [comment]
> sorry, even if its painful, we should avoid the triple exclude list update.. can we maybe create a separate job for it?

it is not painful. Done.

**Comment by toabctl** [comment]
> I can't think of any negative impact it had when we combined the crowbar packages.

Me neither. But merging the git repos into one seems currently not doable without refactoring a lot of things in the ardana CI. So we can use tarscm to combine the sources. But I'm not sure how - all repos in a single one? Not sure if there is something like crowbar-core....

**Comment by aspiers** [comment]
> @toabctl Having a package for each openstack component is a total nightmare. This will coast us so much time when submitting the packages to the SUSE namespace (legal review) and later during maintenance. In maintenance we have to think about all the possible dependencies and this just will cause earlier or later problems.

I'm not sure I understand, but it's good thing that we have to think about dependencies, so that our customers don't have to.  Are you really proposing having all OpenStack components in a single package?  That sounds like it would cause huge nightmares for customers doing updates.  It would be impossible to fix a bug in one component without risking destabilising all others.  Not to mention the huge bloat.

> Basically we do the same mistake again we did with crowbar

No, splitting git repos and splitting packages are two separate things.

> I can't think of any negative impact it had when we combined the crowbar packages.

I can think, it had some huge negative impact :-(  (It had some positive impact too, of course.)

**Comment by toabctl** [comment]
> Looks like it is a separate job now?

Yes. And moved the actual builder code to a macro so we can reuse that for the cloud-trackupstream and ardana-trackupstream job

**Comment by toabctl** [comment]
> I'm not sure I understand, but it's good thing that we have to think about dependencies, so that our customers don't have to. Are you really proposing having all OpenStack components in a single package? That sounds like it would cause huge nightmares for customers doing updates. It would be impossible to fix a bug in one component without risking destabilising all others. Not to mention the huge bloat.

@aspiers This is about the Ardana packages (ansible roles), not OpenStack itself. Basically the same we did with Crowbar (we had crowbar-neutron, crowbar-keystone, ... and now we have just crowbar-openstack). Maybe you misunderstood this?

**Comment by toabctl** [comment]
@rsalevsky so any suggestion how to solve this (given that we can not merge the git repos currently)? I tried ```tar_scm``` but failed (I don't know how to set ```Version:``` in the spec and also I don't know to which value this should be set - @aspiers any idea maybe?).

**Comment by aspiers** [comment]
> @aspiers This is about the Ardana packages (ansible roles), not OpenStack itself. Basically the same we did with Crowbar (we had crowbar-neutron, crowbar-keystone, ... and now we have just crowbar-openstack).

Yeah, merging the Ardana packages into one or two *might* be possible but I think it would require a fundamental change in how Ardana works ... which will be required anyway, because currently Ardana uses Ansible to collect all the Ansible (etc.) repos together and then distribute them to the deployer via `ansible.tgz` inside a huge tarball called something like `hos-5.5.0-20170627T165550Z.tar`.  I think we are going to have to replace that whole build/deploy process with something based on packages and ISOs built by OBS.

> I don't know how to set Version: in the spec

That's what the `set_version` source service is for.

> I don't know to which value this should be set

I haven't heard any team discussions around version strategy yet, but our existing strategy with Crowbar etc. has been working fine AFAIK, so I'd suggest keeping that.

**Comment by toabctl** [comment]
@rsalevsky updated the list of packages. Could you please review again?

**Comment by charleswang007** [comment]
I've created packages for ALL ardana/* repos as listed in http://git.suse.provo.cloud/cgit EXCEPT for below packages:

ardana-dev-tools (discussed not to make package for this)
ardana-opsconsole-server (no LICENSE)
ardana-opsconsole-ui (no LICENSE)
ardana-qa-tests (no executable script)
ardana-swiftlm (no executable script)
ardana-extensions-dcn (no hp/opensource branch)
ardana-extensions-example (no hp/opensource branch)
ardana-extensions-genswitch (no hp/opensource branch)
ardana-extensions-odl (no hp/opensource branch)
ardana-zzz-rebranding (discussed not to make package for this)

Detail error log can be found here: https://build.suse.de/project/show/home:charleswang007007:branches:Devel:Cloud:8

**Pull request merged**
