### PR TITLE
qa_crowbarsetup: avoid ssh warnings

### PR DESCRIPTION
**Pull request by bmwiedemann**
about sleshammer ssh-host-key

### CODE REVIEW

**Comment by aspiers** [comment]
+1, thanks! :)

**Comment by jdsn** [comment]
Maybe rather prevent the ssh invocations to write the known_hosts file (or maybe additionally).
This could be added to the default ssh options: `-o "UserKnownHostsFile /dev/null"`

**Comment by jdsn** [comment]
sorry, did not meant to close it

**Comment by bmwiedemann** [comment]
implemented the nicer UserKnownHostsFile variant

**Comment by jdsn** [comment]
:+1:

**Comment by aspiers** [comment]
@jdsn Please do not merge PRs before the gate has run! Even Travis has not run yet ...

**Pull request merged**
