### PR TITLE
drop install_crowbar_init

### PR DESCRIPTION
**Pull request by MaximilianMeister**
the `crowbar-core` and `crowbar-init` package are now responsible of the symbolic links

### CODE REVIEW

**Comment by rsalevsky** [comment]
I think we can also drop the want_postgresql variable.

**Comment by MaximilianMeister** [comment]
> I think we can also drop the want_postgresql variable.

yeah probably, but it is still used in the old upgrade CI

**Comment by rsalevsky** [comment]
@MaximilianMeister Right, but it is anyway broken and we will not fix it. I would suggest to create a new PR for this and let's discuss there.

**Comment by rsalevsky** [comment]
Gating passed critical part already.

**Comment by skazi0** [comment]
[(3) S50P13 #14 Create/Connect Crowbar DB: Service Integration](https://trello.com/c/tslrmrBm/157-3-s50p13-14-create-connect-crowbar-db-service-integration)

**Pull request merged**
