### PR TITLE
Fix logrotate of testbuild-pr-trigger

### PR DESCRIPTION
**Pull request by dirkmueller**
Without a logrotate, the job can not be accessed anymore from the webui
it has too many builds in the backlog and it just times out.

Also convert to JJB.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by aspiers** [comment]
I would have preferred the change to JJB to be in a separate commit as it's not easy to see the logrotate-related change here (and I'm stupid so I can't understand the commit message without seeing the code change).

**Comment by dirkmueller** [comment]
@aspiers the fix is https://github.com/SUSE-Cloud/automation/pull/985/files#diff-65e841a9412f0868f39cc2433406e26eR22

**Comment by aspiers** [comment]
Yeah thanks - I found it after a small bit of looking.  The principle of one change per commit still applies though ;-)  Also I have to admit I still don't understand why the logrotate helps - I'm probably missing something obvious.

**Comment by dirkmueller** [comment]
@aspiers jenkins keeps a history of jobs for trending, searching and so on. there was a plugin installed that makes the history searchable, and it seems to index all jobs on first access or so, which, when the history is too long, takes longer than the browser timeout and generally causes hangs of jenkins.

**Comment by dirkmueller** [comment]
@aspiers splitted into two commits

**Comment by rsalevsky** [comment]
Still +1

**Comment by aspiers** [comment]
@dirkmueller Thanks a lot, +1 from me (not that you need it).  BTW in future it might be nice to add expanded explanations to the commit messages rather than the PR, so that they are included in the git history without having to go the extra hop to github for the full explanation.

**Comment by dirkmueller** [comment]
@aspiers I think the current git commit message is still good enough..

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
