### PR TITLE
openstack-ardana: add extra_params parameter

### PR DESCRIPTION
**Pull request by stefannica**
Add an `extra_params` job parameter to all Ardana jobs to be used
as a means of injecting additional parameters into existing Jenkins
job. The extra parameters will be reflected in the list of Jenkins
environment variables and also ansible variables for jobs that are
implemented using ansible.
    
The new parameter can be used for various purposes:
 - as an alternative to testing changes to JJB job parameters that
 does not require updating the official Jenkins jobs or creating
 temporary copies of official jobs in order to test e.g. new job
 parameters. This will support running customized versions of the
 "CI for CI" gating job
 - to run job builds that use custom values for global ansible
 variables or shell environment variables that are not otherwise
 reflected in the existing job parameters (the `openstack-ardana-image-update`
 job is modified in this PR to exemplify this).

The new parameter will also remove the need to update the JJB
definitions with new parameters in order to support all options
available in the back-end scripts. The list of parameters in JJB
files can be kept short, while more advanced options can be unlocked
through the `extra_params` parameter.
    
Partially implements: https://jira.suse.de/browse/SCRD-4307

### CODE REVIEW

**Comment by stefannica** [comment]
Tested with: https://ci.suse.de/blue/organizations/jenkins/openstack-ardana/detail/openstack-ardana/3390/

**Comment by stefannica** [comment]
> Tested with: https://ci.suse.de/blue/organizations/jenkins/openstack-ardana/detail/openstack-ardana/3390/

And with: https://ci.suse.de/blue/organizations/jenkins/openstack-ardana/detail/openstack-ardana/3393/pipeline

**Comment by stefannica** [comment]
rebased

**Comment by JanZerebecki** [comment]
Trying to retrigger travis...

**Pull request merged**
