### PR TITLE
added install dependencies for stestr based qe tests

### PR DESCRIPTION
**Pull request by agreentree**

### CODE REVIEW

**Comment by agreentree** [comment]
those packages are needed in the env for stestr to install in the test venv. this is just for qe automated tests to run, that's why SDK is added with lowest priority.

**Comment by agreentree** [comment]
these packages have to be installed at least once on a newly deployed env in order for any stestr based test to run, hence the need for this merge

**Comment by ramak-suse** [comment]
Ok to merge

**Comment by agreentree** [comment]
cleaned up the SLES-SDK repo's so they can't possibly interfere with any future upgrades here - https://github.com/SUSE-Cloud/automation/pull/2729

**Pull request merged**
