### PR TITLE
qa_crowbarsetup: Make cct novaclient test pass on susecloud7

### PR DESCRIPTION
**Pull request by vuntz**
The fix was mentioned by Tom in
https://github.com/SUSE-Cloud/automation/pull/1002

Co-Authored-By: Thomas Bechtold <tbechtold@suse.com>

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by vmoravec** [comment]
+1

**Comment by vuntz** [comment]
Hrm, we still get "Error: Output: package python-novaclient-test is not installed", it seems :/

**Comment by toabctl** [comment]
> Hrm, we still get "Error: Output: package python-novaclient-test is not installed", it seems :/

Which jobs id is this? Or have you tested it locally?

**Comment by vuntz** [comment]
@toabctl https://ci.suse.de/job/openstack-mkcloud/24318/consoleFull (if I'm not mistaken) Haven't investigated yet

**Comment by toabctl** [comment]
> @toabctl https://ci.suse.de/job/openstack-mkcloud/24318/consoleFull (if I'm not mistaken) Haven't investigated yet

This should fix it: https://github.com/SUSE-Cloud/automation/pull/1017

**Pull request merged**
