### PR TITLE
Deploy cinder-volume on SLE12 for SOC6+up

### PR DESCRIPTION
**Pull request by mjura**
Last change needed to finish
https://trello.com/c/QcOIZeiS/409-5-sle12-make-cinder-roles-deployable-on-sle12

This is possible after https://github.com/crowbar/barclamp-cinder/pull/253 was merged

### CODE REVIEW

**Comment by rsalevsky** [comment]
:+1:

**Comment by bmwiedemann** [comment]
:-1: cinder-volume is not only run on controllers in the past... and you can already deploy multiple of it (which indicates it is not a controller service).

**Comment by mjura** [comment]
@bmwiedemann : This change is only for SC6 make sure that cinder-volume will be tested on SLE12 nodes. In future all roles will be deployed on SLE12 nodes and this changes will be not needed for SC6+up.

**Comment by mjura** [comment]
Ok, then it is not needed, because Storage nodes will be chosen for this role

```
    base["deployment"][@bc_name]["elements"] = {
      "cinder-volume" => storage.map { |x| x.name }
    }
```
Closing this change

**Pull request closed without merging**
