### PR TITLE
Enable deploy sahara by default on jenkins jobs

### PR DESCRIPTION
**Pull request by Itxaka**

### CODE REVIEW

**Comment by Itxaka** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;XuPuEe5D&#x2F;55-8-p4-create-barclamp-for-sahara"> (8) P4: Create Barclamp for Sahara</a>

**Comment by dirkmueller** [comment]
typo in the git commit message. personally I think the default in mkcloud and in jenkins should match.. can we update mkcloud instead?

**Comment by Itxaka** [comment]
@dirkmueller Its done this way so if people launch the proposal step locally it does not install sahara by default to avoid delays into getting their cloud ready, _but_ we always run the tests on jenkins in case something breaks them.

The same should be done with the other components that are actually disabled by default IMO, tests should always be run for them.

**Comment by dirkmueller** [comment]
@Itxaka IMHO then either we should add want_sahara=1 to the -gating job or add a -job-sahara that enables it but leaves it disabled by default. I think its not really nice to have different defaults between local and remote runs.

**Comment by Itxaka** [comment]
@dirkmueller Updated to set sahara deployed by default.

**Pull request merged**
