### PR TITLE
Remove Mitaka references

### PR DESCRIPTION
**Pull request by dirkmueller**
Mitaka is no more, long live mitaka!

### CODE REVIEW

**Comment by rsalevsky** [comment]
Just to clarify this means Mitaka is now merged into the product?

**Comment by toabctl** [comment]
@dirkmueller same question. And are you going to delete Devel:Cloud:7:Mitaka ?

**Comment by dirkmueller** [comment]
@rsalevsky @toabctl if you want to first delete the project before removing the jenkins references to it, fine by me. for me the natural flow would be to first remove the references before tearing the building down.

**Comment by toabctl** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by toabctl** [comment]
triggered a rebuild (last one had timeout during node discovery)

**Comment by dirkmueller** [comment]
since the project now got deleted by @vuntz , I guess its time to merge this..

**Pull request merged**
