### PR TITLE
trackupstream: Remove Juno, add openstack-murano/python-muranoclient

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
For the "Remove Juno" part, an answer to the "Why" would be good in the commit message. E.g. dont we want to backport security updates onto a github fork? Would probably need the setup.py dist hack again that I used earlier, because we rely on tarballs in _service files.

**Comment by dirkmueller** [comment]
@bmwiedemann well, it wasn't tracking juno for ages, so I just removed the leftovers. if you want to use some fork, please enable tracking of that fork..

**Comment by Itxaka** [comment]
@dirkmueller There is no muranoclient on Mitaka and its gonna be a bit diffucult to push it to rpm-packaging as it would be missing _all_ dependencies. May be better to wait for Newton instead for muranoclient.

**Comment by dirkmueller** [comment]
@Itxaka I'm not running python-muranoclient for mitaka. all the python*client packages are excluded anyway, since we're not doing trackupstream there.

**Comment by Itxaka** [comment]
Ugh, yes you are right. Keep thinking that is an include instead of exclude due to the !

**Pull request merged**
