### PR TITLE
Add hostname for debugging

### PR DESCRIPTION
**Pull request by nicolasbock**
mkcloud will now also print the hostname of where it is executing.

### CODE REVIEW

**Comment by nicolasbock** [comment]
Example output:
~~~
+(crowbar.v1:qa_crowbarsetup.sh:1716) do_installcrowbar_cloud6plus(): service crowbar stop
+(crowbar.v1:qa_crowbarsetup.sh:1717) do_installcrowbar_cloud6plus(): service crowbar start
Waiting for: crowbar service to start
  until this condition is true: onadmin_is_crowbar_api_available
  waiting 30 cycles of 10 seconds = 300 seconds
~~~

**Comment by aspiers** [comment]
I'm not convinced this is a good idea.  It repeats the same hostname information over and over again, making the logs noisy and substantially increasing the column width, which is a problem when viewing them in smaller windows.  Shouldn't it be enough to output the hostname once?  Or am I missing something?

**Comment by aspiers** [comment]
Also, please don't assume that `mkcloud` will only ever run on `cloud.suse.de`.  For example remote workers can run it at home.  I know that this PR will not break those usage scenarios, but I just wanted to mention it as it's easy for office workers to forget ;-)

**Comment by nicolasbock** [comment]
We have two sets of functions that run on remote hosts: `onadmin_` and `on_controller_`. I tend to get confused with where things are actually run, but that may very well be just a personal shortcoming :smile:  
I do see your point though, it's definitely adding quite some noise.

**Comment by bmwiedemann** [comment]
maybe patch the onadmin and oncontroller functions instead to add visible markers like

```
vvvv running the below code on admin node vvvv
...
^^^^ end of admin node code ^^^^
```

**Comment by nicolasbock** [comment]
@bmwiedemann Good idea, let me experiment with that approach.

**Comment by aspiers** [comment]
Ah, somehow the first time I reviewed this I missed that you were also adding it to `qa_crowbarsetup.sh`.  There it makes a lot more sense.  But when the code being traced is already visibly coming from `mkcloud`, then we already know it must be running on the admin node - right?  So in that case it adds no value AFAICS.

**Comment by nicolasbock** [comment]
I think that's generally true, except maybe for cases where a `on{admin,controller}_` function calls a long non-prefixed function, in which case the remote context is potentially not visible depending on how many lines of output your screen fits. Of course one just has to scroll up in the output to see where that call came from.

**Comment by nicolasbock** [comment]
I read a bit more through the scripts and indeed it's a lot clearer to me now where things are run. I'll close this PR.

**Comment by aspiers** [comment]
I still think it might be worth having the `qa_crowbarsetup.sh` part of this PR.

**Comment by nicolasbock** [comment]
Let's wait for the gating check and then see whether we like the new output.

**Comment by aspiers** [comment]
Good idea, thanks!

**Comment by nicolasbock** [comment]
@aspiers What do you think? I think I need to work on removing not simply `suse.de` but the domainname instead. Is it too verbose?

**Pull request closed without merging**
