### PR TITLE
Add support for SLE12/SP1 pool/update repos

### PR DESCRIPTION
**Pull request by dirkmueller**
When using a standardized cloud image, those do not contain
the SLES base repos. we need to configure them individually.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by aspiers** [comment]
Doesn't this circumvent the current design which allows complete offline deployment using `sync-repos`?

**Comment by aspiers** [comment]
To clarify: if my home internet connection is temporarily broke, I still want to be able to use `mkcloud`

**Comment by toabctl** [comment]
@aspiers this is for cleanvm, not mkcloud. And cleanvm doesn't support offline deployment.

**Pull request merged**
