### PR TITLE
move help text to correct file and two other small improvements

### PR DESCRIPTION
**Pull request by bmwiedemann**

### CODE REVIEW

**Comment by jdsn** [comment]
:+1: lgtm

**Comment by toabctl** [comment]
+1

**Comment by mjura** [comment]
Changes look ok, but I don't know anything about reasons

**Comment by bmwiedemann** [comment]
@mjura want_sles12 is also used in mkcloud, while the other is just used in qa_crowbarsetup. Also this is just a stub/example for how to do this in the future.

**Pull request merged**
