### PR TITLE
Added CI job for crowbar_register x86 SLE12SP2

### PR DESCRIPTION
**Pull request by abel-navarro**
Remove when all cloud7 jobs are SLE12SP2.

### CODE REVIEW

**Comment by abel-navarro** [comment]
@dirkmueller , this creates a job for crowbar_register on SLE12SP2 (x86). I think we'll have green lights here so the full switch to SP2 can happen soon.

**Comment by abel-navarro** [comment]
Mmm, I guess that's not the right way to do it:
```Duplicate definitions for job 'cloud-mkcloud7-job-crowbar_register-x86_64'```

**Comment by dirkmueller** [comment]
minor nitpick, https://ci.suse.de/view/Cloud/view/Cloud7/ there are more jobs with sle12sp2 infix rather than suffix, so I'd call it something like:

cloud-mkcloud7-job-sle12sp2-crowbar_register-x86_64

**Comment by toabctl** [comment]
I think this one is no longer needed because we switched to SP2 now.  Please reopen if you think it's still needed.

**Pull request closed without merging**
