### PR TITLE
mkcloud/libvirt: use pc-i440fx-2.0 for admin node

### PR DESCRIPTION
**Pull request by bmwiedemann**
to workaround bnc#997358
https://bugzilla.suse.com/show_bug.cgi?id=997358

### CODE REVIEW

**Comment by toabctl** [comment]
@bmwiedemann I trust you :) +1

**Comment by jdsn** [comment]
@bmwiedemann I helped you +1

**Comment by toabctl** [comment]
@bmwiedemann but travis is complaining. some syntax error.

**Comment by bmwiedemann** [comment]
fixed a syntax error... but there is still a problem left with the fixtures not adapting to the qemu installed on the test-system.

**Comment by jdsn** [comment]
Testing the locally (on the test system) installed qemu as part of this test is wrong - it does not prove anything. Either remove the test or change it in a way that it only compares the relevant parts of the generated XML.

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
