### PR TITLE
qa_crowbarsetup: Fix installer call

### PR DESCRIPTION
**Pull request by toabctl**
the route has changed

### CODE REVIEW

**Comment by tboerger** [comment]
Duplicate of https://github.com/SUSE-Cloud/automation/pull/683

**Comment by toabctl** [comment]
No. The fix you mentioned is incomplete.

**Comment by tboerger** [comment]
Oh, you are right, sorry.
:+1:

**Comment by MaximilianMeister** [comment]
:+1: thanks, i have missed that one

**Comment by mjura** [comment]
+1

**Pull request merged**
