### PR TITLE
Fix jenkins-job-build config sample

### PR DESCRIPTION
**Pull request by rhafer**
It seems our setup now needs "query_plugins_info=False" otherwise the update
command fails with an error when trying to query the plugins

### CODE REVIEW

**Comment by bmwiedemann** [comment]
+1

**Comment by aplanas** [comment]
Do this needs to be updated in the current jobs?

**Comment by bmwiedemann** [comment]
@aplanas this is the config used to push jobs to jenkins, so it should not affect the jobs itself.

**Comment by jdsn** [comment]
:+1:

**Comment by aplanas** [comment]
I can see duplication for approval in the new github feature

**Comment by dirkmueller** [comment]
@aplanas the reviewer section doe snot show duplicates

**Pull request merged**
