### PR TITLE
remove safely from service libvirtd start

### PR DESCRIPTION
**Pull request by mimi1vx**
for my system breaks run of mkcloud , I don't have sysv compactibility layer in systemd

### CODE REVIEW

**Comment by jdsn** [comment]
I beg to disagree. If the service command is present then it should be run with safely. If it is not present then it should be skipped.

**Comment by bmwiedemann** [comment]
however, this is complicated by the stupid usrmerge. thus it can be /sbin/service or /usr/sbin/service

**Comment by mimi1vx** [comment]
@jdsn in my system 'service' command always return "* WARNING: libvirtd is already starting" and returncode 1

for service libvirtd stop "* ERROR: libvirtd stopped by something else" and 1

**Comment by aspiers** [comment]
:-1: `safely` should not be removed.

@jdsn @bmwiedemann I don't think this is anything to do with `service` not existing.  `service` command is part of `aaa_base` and should *always* be present and in `root`'s `$PATH`.

According to @mimi1vx's last comment above, the problem is trying to start the service when it's already started.  So the correct fix is simply to do `service libvirtd status` first and only start it if it's not yet started.

**Comment by mimi1vx** [comment]
@aspiers 'service' command is sysv .. on sytem without sysv compactibility inst present or send fake info :) ( it's my  case )

btw. anybody using mkcloud on system without systemd ? maybe switch to 'systemctl' ?

**Comment by aspiers** [comment]
@mimi1vx That's not true, `service` command works both on older openSUSE with pure SysVinit and newer openSUSE based on `systemd`. Based on your error message the problem is something else. Please state exactly which distribution and version you are using, and also the rpm version for the `service` executable.  Finally you should check the `libvirtd` logs.

**Comment by mimi1vx** [comment]
@aspiers I don't use openSUSE or SLE ,

**Comment by aspiers** [comment]
Would be far more useful if you said what you ARE using.  But anyway we don't support any of this code on non-SUSE systems.

**Comment by aspiers** [comment]
AFAIK anyway.  If there is a good reason for us to support other distros, please state what it is.

**Comment by mimi1vx** [comment]
Ok, i close this pull req. And use on my system private branch ..

**Pull request closed without merging**
