### PR TITLE
qa_crowbarsetup: consistent admin node repos

### PR DESCRIPTION
**Pull request by jdsn**
In order to allow mkcloud to be run with a custom clouddata mirror
(using $clouddata variable) the admin node image needs to forget all
repos and add back the repos using $clouddata.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by jdsn** [comment]
Verified by CloudFoundry team to fix their issue
Failure is in testsetup so the repo setup was successful.

**Comment by rsalevsky** [comment]
+1

**Comment by bmwiedemann** [comment]
merged it and triggered https://ci.suse.de/job/openstack-mkcloud/19163/ to test if the ptf repo is still used.

**Pull request merged**
