### PR TITLE
Don't hardcode QA3 shared filesystems

### PR DESCRIPTION
**Pull request by dirkmueller**
The tests are run on QA2 hardwre, and using QA3 shares is
going to fail..

### CODE REVIEW

**Comment by vmoravec** [comment]
+1

**Comment by bmwiedemann** [comment]
where is the code replacing this? I can only find
https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L4118

**Comment by vmoravec** [comment]
@bmwiedemann In the scenario jobs

**Comment by bmwiedemann** [comment]
still cannot find it in git or in https://ci.suse.de/view/Cloud/view/Worker/job/cloud-mkphyscloud-qa-scenario-6a/configure .

**Comment by dirkmueller** [comment]
@bmwiedemann its there now

**Comment by bmwiedemann** [comment]
+1

**Pull request merged**
