### PR TITLE
qa_crowbarsetup: Set image_password for manila tempest setup

### PR DESCRIPTION
**Pull request by toabctl**
The image we use for testing Manila has a hardcoded password.
So set it during deployment.

### CODE REVIEW

**Comment by dirkmueller** [comment]
LGTM (I wonder if we need to check though if manila is deployed already, but that is difficult with the scenario files..)

**Comment by toabctl** [comment]
> LGTM (I wonder if we need to check though if manila is deployed already, but that is difficult with the scenario files..)

We don't need to check. There's a check which sets ```manila=false``` in ```tempest.conf``` in the tempest barclamp.

**Comment by dirkmueller** [comment]
+1

**Comment by mjura** [comment]
+1

**Pull request merged**
