### PR TITLE
update_automation: stick to remote master branch

### PR DESCRIPTION
**Pull request by jdsn**
ignore local changes (they should use a copy of the repo)
and consistently checkout the latest remote master

### CODE REVIEW

**Comment by aspiers** [comment]
Not sure why Travis fails.  Apart from that, +1 although of course this is more dangerous and will always discard local changes. Hopefully no scripts call this by default unless they are only used by Jenkins jobs?

**Comment by bmwiedemann** [comment]
:+1:

**Comment by jdsn** [comment]
@aspiers yes, it is only meant to be used by our jenkins jobs, and the repo thats used for this is meant to be at the latest commit.
We had a worker that did not update for weeks due to local changes. Thats exaclty what we don't want. If somebody wants to test local changes, he can do it in a copy of the checkout - then even update_automation will not break it (the directory is hardcoded, intentionally).

**Comment by jdsn** [comment]
@aspiers travis seems to be broken - yesterday we saw apt-get segfaulting, today it can not fetch pull requests ... no idea whats going on there.

**Comment by jdsn** [comment]
successfully tested on mkcloud host

**Pull request merged**
