### PR TITLE
No longer needed. Nova docker can now detect if docker image is missing

### PR DESCRIPTION
**Pull request by jsuchome**
and pull it itself.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
"can now detect" - also for the oldest version where we support docker - cloud5?

**Comment by jsuchome** [comment]
No, I think this is gonna be cloud6 only. While we were testing Cloud5 (and even earlier Cloud6), that docker pull call was needed.

**Comment by dirkmueller** [comment]
@jsuchome looks like you need to update the PR then to only not doing it for iscloudver 6plus..

**Comment by jsuchome** [comment]
Ah, right

**Comment by vuntz** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
