### PR TITLE
Change scenarios to not be impacted by SSL issues with insecure option

### PR DESCRIPTION
**Pull request by vuntz**
cc @vmoravec

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by vmoravec** [comment]
@vuntz Could you please add fixme comments to the trove scenarios as well?

**Comment by vuntz** [comment]
@vmoravec done

**Comment by vuntz** [comment]
Note that I'm not 100% sure the bits in 2c are enough for trove, but we'll see soon.

**Comment by vmoravec** [comment]
+1 yep

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
