### PR TITLE
Replace bc-template-network only in cloud version 6plus

### PR DESCRIPTION
**Pull request by vmoravec**
Crowbar requires it for cloud5

### CODE REVIEW

**Comment by vmoravec** [comment]
Gating test is not useful here, the code is only run for QA hw clouds.

**Comment by bmwiedemann** [comment]
I prepared this change https://github.com/bmwiedemann/automation/commit/c36145558be1879d3ea30d71e7e1d29113fa18cb but didnt get to test it yet.

**Comment by vmoravec** [comment]
The change I submitted is required now as we started with testing upgrade 5 -> 6. Not sure what your change in the else section does.

**Comment by bmwiedemann** [comment]
it makes the network.json work with cloud5, because some newly required fields in it are not allowed in cloud5.

**Comment by vuntz** [comment]
@bmwiedemann any progress on testing your change? If not, we should just get @vmoravec's patch in...

+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
