### PR TITLE
Add jenkins job for manila

### PR DESCRIPTION
**Pull request by rsalevsky**
Depends on https://github.com/SUSE-Cloud/automation/pull/926

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
+1

**Comment by jdsn** [comment]
:+1:

**Comment by toabctl** [comment]
I thought we add the job to the gating - no?

**Comment by dirkmueller** [comment]
well, its broken right now.. but I agree it should be in gating.

**Comment by MaximilianMeister** [comment]
> I thought we add the job to the gating - no?

can we add it once it is green?

**Comment by jdsn** [comment]
> can we add it once it is green?

Lets add it now to make it visible what needs to be fixed to make gating green.

**Comment by toabctl** [comment]
After our mumble discussion this is obsolete, right?

**Comment by jdsn** [comment]
@toabctl yes

**Pull request closed without merging**
