### PR TITLE
Fix more log parser false positives

### PR DESCRIPTION
**Pull request by aspiers**
Address some false positives in the log parser configuration, and tidy up the `openstack-mkcloud-log-parser-test.yaml` job definition.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
IMHO it would be nicer if we could keep such large files (that will be outdated soon) out of the automation repo. Either make another repo or pull it from another server as needed.

**Comment by aspiers** [comment]
Good point. Is it possible for a job to access the logs of other jobs which already ran? If so we don't need to keep these.

**Comment by jdsn** [comment]
@aspiers yes, the worker should be able to fetch logs from jenkins
Otherwise we could store them in a different git repo (that just collects such artifacts) and fetch it via a raw URL. So we only need to update the url.

**Comment by jdsn** [comment]
@aspiers if we fetch them from jenkins then we need to mark the build to be kept to prevent it from being cleaned up, but $somewhen we might need to clean it up (too many marked jobs). So maybe storing logs in a separate repo is better.

**Comment by aspiers** [comment]
> @aspiers yes, the worker should be able to fetch logs from jenkins

But how?

> if we fetch them from jenkins then we need to mark the build to be kept to prevent it from being cleaned up, but $somewhen we might need to clean it up (too many marked jobs). So maybe storing logs in a separate repo is better.

No, we don't need to keep the logs around for a long time.  They're only for testing stuff in the moment, and `openstack-mkcloud-log-parser-test` has a parameter which points to the sample log to reuse for testing.  If we had direct access to logs from other jobs then it would not be necessary to store copies anywhere.  Putting them in the automation repo was simply the only delivery mechanism I could think of for making them directly available to `openstack-mkcloud-log-parser-test`.  If there is another way then we can scrap that.  But as I already asked, *how* can we do this?

**Comment by aspiers** [comment]
@jdsn @bmwiedemann I just dropped the addition of another sample log from this PR, so it should be non-controversial now.

**Comment by bmwiedemann** [comment]
you can curl https://ci.suse.de/view/Cloud/view/Worker/job/openstack-mkcloud/59064/consoleText from a run

**Comment by aspiers** [comment]
@bmwiedemann Thanks! How come that doesn't require authentication?

**Comment by aspiers** [comment]
@bmwiedemann @jdsn Added a commit to ditch the sample logs and instead directly retrieve logs via `curl`.

**Comment by bmwiedemann** [comment]
@aspiers I think that is because https://ci.suse.de/configureSecurity/ has checkboxes enabled for Anonymous Read access. One "Overall" and one "Jobs"

**Comment by aspiers** [comment]
@bmwiedemann Thought you might like that ;-) Unfortunately `git clone` will still check out the old sample log files.

**Pull request merged**
