### PR TITLE
Added support for heat/magnum on ardana_qe_tests role

### PR DESCRIPTION
**Pull request by ramak-suse**
Added support for both heat and magnum tests. The heat tests have previously been reviewed and fixed(I redid all the changes as I made a procedural mistake before). Fixed now.

### CODE REVIEW

**Comment by dirkmueller** [comment]
can we do this in a way that they're shareable with crowbar? we seem to be building up code duplication for no good reason. 

we also need to separate this out so that we can run the heat stack tests for example against containerized control plane tech preview as well.

**Comment by ramak-suse** [comment]
Currently crowbar does not have any services tests (other than tempest). This should work for crowbar too

**Comment by dirkmueller** [comment]
@ramak-suse just to understand the comment, there are additional service tests in Crowbar, keywords to look for "cct", "testsetup in qa_crowbarsetup.sh". It would be great to consolidate that rather than replication the implementations.

**Comment by mnmehta** [comment]
@dirkmueller: the specific cct issue will be addressed by @kbaikov, but I'm going to make a general comment: the main goal of this phase is to reduce manual work by quickly insert existing QE tests into the framework pretty much as is, unless there are some glaring areas that need immediate fixing. All other work (e.g. long term leverage between crowbar and ardana) will be tracked as QE backlog tickets for future sprints.

**Comment by kbaikov** [comment]
@dirkmueller This is currently just a move of the existing qe tests in this automation repo. So that we use one ansible based framework to run tests and report test results.

cct is not used anymore. 

testsetup function magnum part looks usefull, but it is only run for SOC7. Need to take a look if still relevant.

@ramak-suse Please take a look at what is done in testsetup function here after the line 4017: https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L4017 

@ramak-suse Perhaps you can use it as an inspiration for additional magnum tests.

@ramak-suse @dirkmueller the only other tests that we run on crowbar side are the one in tempest: magnum.tests.functional.api*

**Comment by ramak-suse** [comment]
Redoing some of these changes

**Pull request closed without merging**
