### PR TITLE
Disable test updates for cloud6

### PR DESCRIPTION
**Pull request by dirkmueller**
there is a broken test update in the queue right now, let's
not bother with it.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
FWIW, I already disabled test updates in jenkins.

But the PR helps when we run mkcloud manually, so LGTM.

**Comment by dirkmueller** [comment]
@vuntz how did you disable it in jenkins? I don't see a PR..

**Comment by vuntz** [comment]
> @vuntz how did you disable it in jenkins? I don't see a PR..

In the definition of openstack-mkcloud.

**Pull request merged**
