### PR TITLE
qa_crowbarsetup, scenarios: Do not use l2pop key anymore for Cloud 6

### PR DESCRIPTION
**Pull request by vuntz**
The key is gone after M7.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by jsuchome** [comment]
+1

**Comment by rhafer** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by abel-navarro** [comment]
+1

**Comment by aplanas** [comment]
The `test_volume_boot_pattern` fail is unrelated, so +1

**Pull request merged**
