### PR TITLE
more preparations for running crowbar on sle12

### PR DESCRIPTION
**Pull request by MaximilianMeister**
add SLE12 Cloud repo instead of SLE11

### CODE REVIEW

**Comment by vuntz** [comment]
Unfortunately, we worked in parallel on that and I have a patch for the same thing (although it works differently): https://github.com/SUSE-Cloud/automation/pull/453

**Comment by MaximilianMeister** [comment]
@vuntz I sent you the link to this PR yesterday, so we didn't really work in parallel ;)

**Comment by vuntz** [comment]
Ah, well, I haven't seen it yesterday :/ My fault then.

**Comment by MaximilianMeister** [comment]
closing in favor of https://github.com/SUSE-Cloud/automation/pull/453

**Pull request closed without merging**
