### PR TITLE
QA scenarios and jjb changes

### PR DESCRIPTION
**Pull request by vmoravec**
This PR contains changes only in QA related yaml files:

1. Moves qa scenario related jjb files into separate dir
2. Updates the params for jjb jobs and adds `trigger-builds` section for tests
3. Unifies naming of the qa scenario files
4. Adds scenarios for cloud7 (tested with `develcloud7`, mainly with success, see https://ci.suse.de/view/Cloud/view/QA/

JJB job changes have been tested on QA hardware, see the view above.

Will add documentation if needed once https://github.com/SUSE-Cloud/automation/pull/949 reviewed and merged.

### CODE REVIEW

**Comment by vmoravec** [comment]
Codeclimate issues will be resolved later during the next milestone(s) testing.

**Comment by kbaikov** [comment]
+1
Thats a lot of stuff for just 2 commits.

**Comment by jsuchome** [comment]
+1

**Comment by vmoravec** [comment]
@kbaikov agree, but this is a one-time special case due to consolidation of all of the files, will avoid it definitely in the future. Thanks!

**Pull request merged**
