### PR TITLE
qa_crowbarsetup: better wait for volume-create to finish

### PR DESCRIPTION
**Pull request by bmwiedemann**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
should help avoid http://ci.suse.de/view/Cloud/view/Worker/job/openstack-mkcloud/2485/console

**Comment by vuntz** [comment]
Not tested, but LGTM.

**Comment by bmwiedemann** [comment]
tested it now

**Comment by jdsn** [comment]
:+1: now it looks good :)

**Pull request merged**
