### PR TITLE
Fix libvirtd configuration and startup

### PR DESCRIPTION
**Pull request by aspiers**
Previous logic made unreliable assumptions about the existing
contents of libvirtd.conf.

### CODE REVIEW

**Comment by jdsn** [comment]
:+1:

**Comment by bmwiedemann** [comment]
IMHO too much adde code complexity for a case that very few people will hit.
would be easier with an add-or-change-value helper

**Comment by aspiers** [comment]
@bmwiedemann Huh? `confset` *is* the add-or-change-value helper. 

This fixes a real world problem I encountered.  If you don't like the approach, I'm open to alternatives so please suggest one.

**Comment by jdsn** [comment]
@bmwiedemann The code is longer, surely. But it solves the issue that exactly these "few people" hit that you are talking about.

**Comment by bmwiedemann** [comment]
augeas would have been nice to use, but unfortunately it seems to be missing
https://www.redhat.com/archives/libvir-list/2008-August/msg00639.html

**Comment by aspiers** [comment]
Works for me and no alternative suggested -> merging.

**Pull request merged**
