### PR TITLE
Move qa scenarios into separate dir qa/ssl-insecure

### PR DESCRIPTION
**Pull request by vmoravec**
All current scenarios are configured to use `ssl` with `insecure` option. We are missing scenarios without `ssl` completely and with `ssl` with non-self-generated certs.
So, next steps will be new scenarios in dir `qa/no-ssl` and `qa/ssl`.
The goal is to have separate scenarios globally for no-ssl, ssl and ssl-insecure setup.

### CODE REVIEW

**Comment by vuntz** [comment]
If it's useful for QA, then +1 from me.

**Comment by bmwiedemann** [comment]
wouldnt this move need changes to the jenkins jobs, too, so that it can find the yaml files again?

**Comment by vmoravec** [comment]
@bmwiedemann yes, that's the plan

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
