### PR TITLE
Add possibility to skip manila deployment

### PR DESCRIPTION
**Pull request by toabctl**
"want_manila" is a new env var (default '1') which can be set to 0
to disable manila deployment.

### CODE REVIEW

**Comment by toabctl** [comment]
@vuntz this hopefully solves the docker scenario

**Comment by aplanas** [comment]
+1 for the second commit, why the first one?

**Comment by toabctl** [comment]
@aplanas to have the possibility to skip manila if needed.

**Comment by aplanas** [comment]
> to have the possibility to skip manila if needed.

Yeah, sure. That was clear reading the title. But why?

Are there test scenarios where manila tempest is not running OK? To speed some other tests? Add a one degree of freedom for local deployments?

**Comment by toabctl** [comment]
@aplanas Just thought it's a good idea to have it. But I'll remove it.

**Comment by toabctl** [comment]
@aplanas fixed.

**Comment by aplanas** [comment]
> But I'll remove it.

Oh no, do not remove it : )

+1

**Comment by vuntz** [comment]
@toabctl if you still have your first commit, I think it's fine to put it back. Otherwise, +1 the way it is right now.

**Pull request merged**
