### PR TITLE
Move the bulk of the openstack-* jobs to scripts

### PR DESCRIPTION
**Pull request by jesusaurus**
By moving the bulk of this jenkins job to a dedicated script within the
automation repo, future changes to the job can be self-tested.

### CODE REVIEW

**Comment by dirkmueller** [comment]
@jesusaurus is it possible to split this into a crowbar and an ardana piece? just for not breaking both at the same time? :-)

**Comment by jesusaurus** [comment]
This is not very useful after #2701

**Comment by jesusaurus** [comment]
Since #2701 only addresses the openstack-ardana job, I'll keep this open to address the openstack-mkcloud job

**Comment by JanZerebecki** [comment]
I can't reopen this. Maybe you need to create a new PR as this ones branch changed while it was open?

**Pull request closed without merging**
