### PR TITLE
qa_crowbarsetup.sh: Deploy rabbitmq-server on SLE12

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by vuntz** [comment]
+1 (even though I'd put it between database and keystone, but that doesn't matter much)

**Comment by dirkmueller** [comment]
@vuntz changed

**Comment by vuntz** [comment]
(still +1, obviously)

**Comment by dirkmueller** [comment]
jenkins says Green, so lets merge it, as its blocking my card from getting done

**Pull request merged**
