### PR TITLE
mkcloud: prepare for the nondisruptive upgrade

### PR DESCRIPTION
**Pull request by jdsn**
proposed alternative to PR #1234

### CODE REVIEW

**Comment by jsuchome** [comment]
OK, yes, I would agree with this alternative. +1

**Comment by jsuchome** [comment]
But please wait with merging until we decide that alternative options for 6-7 are actually required.

**Comment by jdsn** [comment]
> But please wait with merging until we decide that alternative options for 6-7 are actually required.

If not, why did you create the original PR in the first place?

**Comment by jsuchome** [comment]
> > But please wait with merging until we decide that alternative options for 6-7 are actually required.
> If not, why did you create the original PR in the first place?

Because discussions are taking too long and it's good to have PR prepared in time (at least gating could be started).

But as it seems from https://github.com/crowbar/crowbar-core/pull/662 , we're gonna use it.

**Comment by jsuchome** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;BfMFXB3r&#x2F;64-5-s47p5-s48p19-add-ci-jobs-for-new-upgrade-process-with-and-without-ha"> (5) S47P5 (S48P19) Add CI jobs for new upgrade process with and without HA</a>

**Pull request merged**
