### PR TITLE
Add heat client to instructions

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

### CODE REVIEW

**Comment by bmwiedemann** [comment]
Did something change in openstackclient? On Leap 15.0 I see
```bash
rpm -q --requires python2-openstackclient | grep heat
python2-heatclient >= 1.10.0
```

so this change should not be needed.

**Comment by nicolasbock** [comment]
Ah, ok. I might have run into this installing it the other way around, i.e. installing the heat client first and then noticing that the openstack client was missing :slightly_frowning_face:

**Comment by nicolasbock** [comment]
I'll double check

**Comment by nicolasbock** [comment]
Closing, not necessary.

**Pull request closed without merging**
