### PR TITLE
Update iSCSIctl to SLE 12

### PR DESCRIPTION
**Pull request by aplanas**

### CODE REVIEW

**Comment by jsuchome** [comment]
Works well for me +1

**Comment by vuntz** [comment]
Do we want to keep SLE11 compatibility or not? (Not sure it's worth it, but we could have the sle11 version living as a separate script)

**Comment by aplanas** [comment]
@vuntz, good question. I think that SLE11 is not relevant for this script, according QA, but I will re-ask

**Comment by mimi1vx** [comment]
for QAM, all ckoud virtualization hosts using SLE12

**Comment by vuntz** [comment]
Not really a real +1 since I'm not reviewing the code, but if it works, then I'd say it's okay to merge.

**Comment by vuntz** [comment]
Didn't see anything wrong, so LGTM.

**Comment by vuntz** [comment]
@aplanas did you check with QA about the SLE11 bit?

**Comment by vuntz** [comment]
Merged; if there's any need for a SLE11 variant, we can resurrect it.

**Pull request merged**
