### PR TITLE
qa_crowbarsetup: set rootpw via proposal (bsc#964624)

### PR DESCRIPTION
**Pull request by bmwiedemann**
this is a cleaner approach, reflecting the way a customer would set this.

### CODE REVIEW

**Comment by dirkmueller** [comment]
+1

**Comment by vuntz** [comment]
+1

**Comment by aplanas** [comment]
can we use `openssl passwd -1 -salt ...` to generate hashes, instead of c&p? In this way we can write something like:

`proposal_set_value provisioner default "['attributes']['provisioner']['root_password_hash']" $(passwdhash "linux")` (or the proper way in bash)

**Comment by bmwiedemann** [comment]
@aplanas  adjusted to not use a pre-hashed PW

**Comment by aplanas** [comment]
@bmwiedemann uau thanks!

+1

**Pull request merged**
