### PR TITLE
qa_crowbarsetup: unify crowbar upgrade api requests

### PR DESCRIPTION
**Pull request by jdsn**
refactor requests to crowbar upgrade api
followup of PR #1086

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
lets see what gating says

but the code looks good, thanks!

+1

**Comment by nicolasbock** [comment]
+1

**Comment by MaximilianMeister** [comment]
upgrade gating failed other than expected (with return code 000). maybe the curlopts are wrongly escaped? they look a bit malformed with all the quotes

**Comment by nicolasbock** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by MaximilianMeister** [comment]
@toabctl there was still some error in the quoting or somewhere I guess, beacause it was expected to return 422, not 500 like in the last run of https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-upgrade-x86_64/

**Comment by jdsn** [comment]
@toabctl there was a gating build still running (icon yellow) ...

**Pull request merged**
