### PR TITLE
Switch to a build-trigger instead of a post-build-trigger

### PR DESCRIPTION
**Pull request by dirkmueller**
This way one can at least see that the trigger is still
running.

### CODE REVIEW

**Comment by aspiers** [comment]
+1 as per http://mailman.suse.de/mlarch/SuSE/cloud-devel/2015/cloud-devel.2015.08/msg00004.html - thanks!

**Comment by aplanas** [comment]
Is this fixed via the Jenkins web, or manually? I would like to fix the rest of the triggers.

**Comment by dirkmueller** [comment]
@aplanas you can do both. first fix the file here, and then get it uploaded to jenkins, or change it in jenkins and then download it (and PR it)

**Comment by aplanas** [comment]
@dirkmueller IUC the XMLs from Jenkins are stored automatically in https://github.com/SUSE-Cloud/automation/tree/jenkins branch. So this same XML is in https://github.com/SUSE-Cloud/automation/commit/b41b106505227ae477ac5e475548a13436b6f190

If that is the case I would vote to close this PR and update the XMLs from Jenkins itself

**Comment by dirkmueller** [comment]
@aplanas thats just a backup method since we don't actually know who or when the jenkins configuration is changed on the server (and everyone has privileges to do so). so the jenkins branch is sometimes the only method of understanding why things are suddenly broken. 

I think it still makes sense to have the actual jenkins changes in git (branch master) as it will have useful commit logs and makes git blame easier.

**Comment by aspiers** [comment]
I strongly agree with @dirkmueller.  Making changes directly on Jenkins is very error-prone, especially considering there are no individual accounts on ci.suse.de.  And anyway I think making the changes in git `master` must be the currently accepted way of doing it, otherwise there would be no reason to have the XML in git `master` at all (since like you say it is automatically backed up in the `jenkins` branch).

**Pull request merged**
