### PR TITLE
qa_crowbarsetup: allow to use custom network.json

### PR DESCRIPTION
**Pull request by bmwiedemann**

### CODE REVIEW

**Comment by matelakat** [comment]
[explicit network.json file](https://trello.com/c/twadEize/76-explicit-networkjson-file)

**Comment by nicolasbock** [comment]
@matelakat Getting Trello card not found?

**Comment by matelakat** [comment]
> @matelakat Getting Trello card not found?

it's on the SAP board

**Comment by nicolasbock** [comment]
@matelakat I guess I am not allowed to see it then.

**Comment by rsalevsky** [comment]
Needs a rebase

**Comment by bmwiedemann** [comment]
rebased

**Pull request merged**
