### PR TITLE
Update QA test scenarios to Cloud 8

### PR DESCRIPTION
**Pull request by spacefito**
This is still very much a WIP. first pr is to setup directory structure and yaml files

### CODE REVIEW

**Comment by aplanas** [comment]
Can you rename the WIP commit?

**Comment by aplanas** [comment]
@gosipyan pointed me that QA needs to change also some scripts in the gating, but that those scripts are not public. Gayane, do you have any news?

**Comment by gosipyan** [comment]
Big thanks for updating  scenarios :) After this we also need update crowbar vm image to sp3 but usually we do it only when official version released so PR can be merged but actual run would be later I guess. @kbaikov @vmoravec  please correct me if I am wrong .

**Comment by aplanas** [comment]
Can you update the rest of the jobs. A `grep -R -A1 'name: cloud_version'` shows that we need to update also:

* cloud-mkphyscloud-qa-scenario-6a.yaml
* cloud-mkphyscloud-qa-scenario-3.yaml
* cloud-mkphyscloud-qa-scenario-9.yaml

**Comment by spacefito** [comment]
Added the rest of necessary yaml files and also updated admin_os to sles12sp3

**Comment by aplanas** [comment]
The rebase goes wrong

**Comment by spacefito** [comment]
@aplanas  ? "rebase goes wrong" ... sorry don't follow. pc/cloud8 is 5 commits ahead of this master. and there does not seem to be a divergence.

**Comment by aplanas** [comment]
@spacefito you can see in the PR that there are 53 commits, but we only expect 1 or 2. There is even a merge commit, that can explain the problem in your rebase.

**Comment by spacefito** [comment]
@aplanas  you are right. The strange thing is that if I look at it from my branch it says that there is only 5 commits. not 53. Let me try to clean this up, it shoudl only be two commits anyways. 
see: 

(automation) adolfo@duartelab:~/upstream/automation> git remote -v 
origin	https://github.com/spacefito/automation.git (fetch)
origin	https://github.com/spacefito/automation.git (push)
upstream	https://github.com/SUSE-Cloud/automation.git (fetch)
upstream	https://github.com/SUSE-Cloud/automation.git (push)
(automation) adolfo@duartelab:~/upstream/automation> git log --oneline upstream/master..origin/pr/cloud8
7067f0fd Merge branch 'pr/cloud8' of https://github.com/spacefito/automation into pr/cloud8
00e515f6 Set default cloud version to 8 for qa scenarios
8ba6e6c5 Update QA test scenarios to Cloud 8
433cbd87 Set default cloud version to 8 for qa scenarios
c1eec1e2 WIP: Update QA test scenarios to Cloud 8
(automation) adolfo@duartelab:~/upstream/automation>

**Comment by aplanas** [comment]
you can use `gitk` to have a better understanding of the problem and use `git rebase -i` to try to fix the issue

**Comment by spacefito** [comment]
@aplanas  take a look at this: https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch
looks like the issue is due to the fact that github looks at common ancestor to figureout the commits count.

So even I do a git rebase upstream/master into my pr/cloud8 branch, that only copies the commits to my branch.  the common ancestor will still be the original one (51 commits ago) 

so github is design that way.. 
what command do you use to rebase your branches? 
I used "get rebase upstream/master"

**Comment by spacefito** [comment]
@aplanas  if you really want I can create a new PR and that will show the correct commit count under the PR.

**Comment by aplanas** [comment]
For me looks like that the problem is not that, but the commit that you have here:

https://github.com/spacefito/automation/commit/7067f0fd1088dcb7a67e898f9ef99c9c405eea1f

This is a merge, not a rebase. I think that you need to drop this merge, and make sure that you rebase your branch with your current master

**Comment by aplanas** [comment]
No need to close this PR, we can fix it : ))

**Comment by spacefito** [comment]
I had to use the push -f flag.

**Comment by spacefito** [comment]
now let me get rid of the other commits and do it again.

**Comment by spacefito** [comment]
alright. that did it. I had to reset my local head to get rid of the merge and then use a push -f so that it does not show up all the other commits (which came from upstream/master anyways).

**Comment by aplanas** [comment]
Cool!

**Comment by jsuchome** [comment]
Just a note; I did not go through the code change, but be aware of the fact that ceph requires at least 2 nodes and all need to be deployed with SP2.

**Comment by aplanas** [comment]
@jsuchome good point, but the sle12sp3 reference is about the admin node. I think that if the logic is in qa_crowbarsetup.sh, this will work.

We launched 1a (HA scenario) in qa2 and is red because a bug in swift. For now is a bit hard to test more, because qa2, qa3 and qa4 are reserved.

IMHO is good to merge, and if QA find something we can help later.

**Comment by aplanas** [comment]
@vuntz / @rsalevsky can someone with rights evaluate the merge?

**Pull request merged**
