### PR TITLE
Add gitlint check to automation (SOC-9559)

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by JanZerebecki** [comment]
See also discussion in https://github.com/SUSE-Cloud/automation/pull/2720

**Comment by rsalevsky** [comment]
@JanZerebecki Feel free to propose a change to the gitlint config. I just want that we follow the current policy and therefore follow the rules.

**Comment by dirkmueller** [comment]
Automation repository is used for many different purposes other than what the release engineering team cares about (like for example community usecases). Enforcement.of a jira ticket for that is IMHO preventing contribution. 

I do embrace the idea of useful commit message, which is why rationales need to be listed in the git commit message, rather than checking whether there is a jira ticket reference but then have no useful commit message itself and the require to look up the ticket, which might not have the right information either.

I think we need to handle this by human reviews enforcement of reasonable commit messages

**Comment by rsalevsky** [comment]
I will do some changes to this to make it more generic.

**Comment by JanZerebecki** [comment]
It would work for this repo if you remove the groups `[title-match-regex]` and `[author-valid-email]` from the `gitlint.ini`. That means having a different `gitlint.ini` for this and the ardana repos.

**Comment by JanZerebecki** [comment]
See also https://github.com/SUSE-Cloud/automation/pull/3509 which does exactly those changes to `gitlint.ini`.

**Comment by rsalevsky** [comment]
Test

**Comment by rsalevsky** [comment]
Test

**Comment by rsalevsky** [comment]
1: T7 Title does not match regex)

**Comment by stefannica** [comment]
1: T7 Title does not match regex (^(?!SOC).*\((((bsc#|SOC-)[0-9]+(,\s)?)+|trivial|typo|noref)\)$)

**Comment by rsalevsky** [comment]
1: T7 Title does not match regex (^(?!SOC).*((((bsc#|SOC-)[0-9]+(s)?)+|trivial|typo|noref)))

**Comment by rsalevsky** [comment]
1: T7 Title does not match regex (^(?!SOC).*\/((((bsc#|SOC-)[0-9]+(,\/s)?)+|trivial|typo|noref)\/)$)

**Comment by JanZerebecki** [comment]
I never look there when it's not failing. So I don't see any sense in its result being ignored.

**Pull request closed without merging**
