### PR TITLE
Set the build name again on the submit job

### PR DESCRIPTION
**Pull request by dirkmueller**
This makes it easier to figure out which :Staging
project got merged recently.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by toabctl** [comment]
@bmwiedemann @jdsn opinions?

**Comment by bmwiedemann** [comment]
maybe leave out the Cloud:OpenStack: part as it is redundant with zero information

**Comment by jdsn** [comment]
> maybe leave out the Cloud:OpenStack: part as it is redundant with zero information
 ... or shorten it to `C:O:`

Sure +1  (with shortened C:O: it is even a +1.1

**Comment by dirkmueller** [comment]
adjusted.

**Pull request merged**
