### PR TITLE
Add helper for triggering test builds of github PRs

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
LGTM besides the flake8 errors

not sure but does it make sense to put the constants into a `yml` file to make it reusable for other machines or scenarios?

**Comment by dirkmueller** [comment]
@MaximilianMeister yes, eventually this makes sense. I've been thinking about this but weren't able to come up with an extensible format that could be used for more than just one purpose. If you have other code in mind that could benefit from sharing that config data, we can take a look at refactoring those two tools then.

**Comment by MaximilianMeister** [comment]
@dirkmueller to be honest I haven't even thought about the other tool when I wrote my comment. it was really just for this tool here. but yes it would be good to bring the tools together somehow at a later point.

**Comment by rsalevsky** [comment]
LGTM

**Comment by bmwiedemann** [comment]
:+1: looks as if it cannot break much

**Pull request merged**
