### PR TITLE
mkcloud: use RSA instead of DSA and push other pubkeys into admin node

### PR DESCRIPTION
**Pull request by bmwiedemann**
for SLES12-SP2 we have openssh-7.2 which blocks ssh-dss keys by default
so we also upload rsa keys

### CODE REVIEW

**Comment by jdsn** [comment]
:+1:

**Comment by MaximilianMeister** [comment]
+1 tested and works

**Comment by jsuchome** [comment]
Hm, doesn't seem to be enough for me at `mkchi`, I'm still getting connection refused...

**Comment by bmwiedemann** [comment]
merged anyway as it did not break things and seems to improve the situation in other places

**Pull request merged**
