### PR TITLE
Make sure we do not use SP1 nodes for ceilometer-agent

### PR DESCRIPTION
**Pull request by jsuchome**
This should fix failures like https://ci.suse.de/job/openstack-mkcloud/31941/console

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by toabctl** [comment]
@jsuchome what's the problem with using ceilometer-agent on a SP1 node? What about other services?

**Comment by jsuchome** [comment]
Other services are mostly solved already, see also this PR for some other checks.
SP1 nodes are for ceph only and we do not even have Cloud repository (with openstack packages) for them

**Comment by toabctl** [comment]
+1

**Pull request merged**
