### PR TITLE
Enable L2 population for DVR deployment

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by aplanas** [comment]
Why this change? AFAIK this is needed only for GRE and VXLAN, as it is now.

**Comment by mjura** [comment]
@aplanas Look on this line in `qa_crowbarsetup.sh` https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L2694

**Comment by mjura** [comment]
This is needed to fix https://ci.suse.de/view/Cloud/view/Builds/job/cloud-mkcloud7-job-dvr-x86_64/

**Comment by aplanas** [comment]
I can see that the job have

`networkingmode=vlan`

The line that you shows me set that the user can have the three alternatives, but if I understand correctly only `vlan` will be set. So maybe jenkins is showing a real error here in the validator, but your code will hide it.

**Comment by dirkmueller** [comment]
@aplanas the change is correct, l2pop is required when tunneling based type drivers are enabled, which means that either vxlan or gre are enabled. this is always the case as we always enable all in our config. what the default tenant network type is is totally irrelevant.

**Comment by mjura** [comment]
I've added more info into commit message and commented the code

**Comment by mjura** [comment]
@aplanas In mkcloud we are enabling all `ml2_type_drivers' = ['gre','vxlan','vlan']`, it means that for DVR L2 population has to be also enabled always

**Pull request merged**
