### PR TITLE
Add want_dvr parameter and default it to 1.

### PR DESCRIPTION
**Pull request by aplanas**

### CODE REVIEW

**Comment by vuntz** [comment]
Hrm, I don't think we want it to be the default -- it's a tech preview option that is off by default, and therefore should not be our default testing.

**Comment by aplanas** [comment]
* Remove the default value of 1 for want_dvr
* Update commit message

**Comment by jsuchome** [comment]
+1

**Comment by jdsn** [comment]
FYI: Everything scripts/jenkins/{ci.suse.de,ci.opensuse.org,river.suse.de} is a backup.

**Pull request merged**
