### PR TITLE
Add socok8s-trackupstream job

### PR DESCRIPTION
**Pull request by toabctl**
Similar to openstack-trackupstream and cloud-trackupstream, a new job
called soco-trackupstream is added.
This job will periodically update the Cloud:socok8s:master/socok8s RPM
package from the git source defined in the _service file.
This is needed to get an updated ISO with the latest socok8s code on a
daily base.

### CODE REVIEW

**Comment by toabctl** [comment]
Job deployed, but change to track-upstream.sh untested

**Comment by rsalevsky** [comment]
I had the idea to only use Pipeline Jobs for Cloud 10 as they are easier to connect with each other. If this is urgent we can go ahead and merge this but we might change it later again.

**Comment by dirkmueller** [comment]
@rsalevsky this is a job on ci.o.org, no pipelines there

**Comment by rsalevsky** [comment]
> @rsalevsky this is a job on ci.o.org, no pipelines there

And? Doesn't mean we can't change that or at least think about it.

**Comment by toabctl** [comment]
Followup to hopefully fix the job is https://github.com/SUSE-Cloud/automation/pull/3618

**Pull request merged**
