### PR TITLE
Set SLES12SP2 as default platform for Cloud7+

### PR DESCRIPTION
**Pull request by abel-navarro**
Rebased work from https://github.com/SUSE-Cloud/automation/pull/1033

### CODE REVIEW

**Comment by abel-navarro** [comment]
CI failed: https://ci.suse.de/job/openstack-mkcloud/28809
I'm rebuilding while investigating it.

**Comment by dirkmueller** [comment]
@abel-navarro please note that crowbar-register needs fixing before switching to SP2..

**Comment by abel-navarro** [comment]
@dirkmueller I'll check that, although I think it passed that point since it failed with cinder volumes testing.

**Comment by dirkmueller** [comment]
@abel-navarro with crowbar-register I mean the job that uses crowbar-register, it doesn't deploy cinder so that must be something else

**Comment by abel-navarro** [comment]
@dirkmueller the [CI job for crowbar-register](https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-crowbar_register-x86_64/) seems to have green light (as of today). Both admin and non-admin nodes run SLE12SP2.

**Comment by rsalevsky** [comment]
@abel-navarro There still seams to be a problem while rebooting the cloud. See https://ci.suse.de/job/openstack-mkcloud/28892/console

**Comment by abel-navarro** [comment]
@rsalevsky that job doesn't look related to this PR. Could you provide more insight?

**Comment by rsalevsky** [comment]
@abel-navarro It's a normal gating job with SP2 enabled. See https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-sle12sp2-x86_64/

**Comment by dguitarbite** [comment]
What about storage repositories? I remember having issues with storage repos for Cloud 7.

**Comment by rsalevsky** [comment]
+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
