### PR TITLE
mkcloud: consistently use [[ $var ]]

### PR DESCRIPTION
**Pull request by bmwiedemann**
instead of [[ -n "$var" ]] etc

### CODE REVIEW

**Comment by jdsn** [comment]
:+1: thanks

**Comment by jdsn** [comment]
even better now :)   +10

**Comment by aspiers** [comment]
If you want this style to stick then I strongly suggest setting up some CI for it.  I'm not sure if https://docs.codeclimate.com/docs/shellcheck can help with this - probably not, but it would be well worth setting up anyway :)

**Comment by nicolasbock** [comment]
+1

**Comment by Itxaka** [comment]
@bmwiedemann may need to rebase + fix as https://github.com/SUSE-Cloud/automation/pull/1206 got in.

Anyway, +1

**Pull request merged**
