### PR TITLE
create sqlite db and migrate postgresql data for devsetup

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by aplanas** [comment]
Why to move from psql to sqlite?

**Comment by MaximilianMeister** [comment]
> Why to move from psql to sqlite?

this is necessary only for the development environment in rails, usually you have sqlite for `RAILS_ENV=development`. we keep psql for production

**Comment by rsalevsky** [comment]
We should also switch in the dev environment to PostgreSQL.

**Comment by aplanas** [comment]
> this is necessary only for the development environment in rails

Ah but this is dangerous. Sqlite is really cool but don't give a heck about most of the constraints (you can insert an integer in a text field). The code that works on devel can not work on production

**Comment by MaximilianMeister** [comment]
> Sqlite is really cool but don't give a heck about most of the constraints (you can insert an integer in a text field). The code that works on devel can not work on production

we had SQLite before for production, but you're right it could create some weird cases in `development` mode, which don't exist in `production`. but as @rsalevsky said it's better to switch the other way around (but the change will be in crowbar in the rails config)

**Pull request closed without merging**
