### PR TITLE
Refactors libvirt_setup.py

### PR DESCRIPTION
**Pull request by dguitarbite**
Superseeds  #364

Breaks down the patch into multiple commits.

### CODE REVIEW

**Comment by aplanas** [comment]
Why close the other one? IMHO there where good points in the comments that still apply in this commit.

**Comment by jdsn** [comment]
Breaking one commit into multiple commits {c,sh}ould have been done in the original PR. Please take the comments from there into account.

**Comment by aspiers** [comment]
Agree with @jdsn, please see http://blog.adamspiers.org/2015/03/24/why-and-how-to-correctly-amend-github-pull-requests/

**Comment by dguitarbite** [comment]
@aspiers @jdsn What do you suggest? Should I move this back to the original PR or continue here? I will ofcourse address all the comments in this and previous PR. I think I did address most of the comments and suggestions in the previous PR.

**Comment by aspiers** [comment]
It doesn't make much difference now - I guess just continue here.  I think we were both mainly mentioning it for the future.

**Comment by dguitarbite** [comment]
Yes, I will follow this in future. Thanks :).

**Comment by dguitarbite** [comment]
Seems to pass the jenkins build https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/4224/console

**Comment by jdsn** [comment]
please rebase, this PR contains commits from Bernhard that have already been merged

**Comment by dguitarbite** [comment]
@jdsn I have removed the merged commits.

**Comment by dguitarbite** [comment]
@toabctl https://github.com/SUSE-Cloud/automation/commit/c4768bad3e0cc0ca87702bd171026ce8aecdbc23

**Comment by jdsn** [comment]
:+1: PR test running: https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/4293

**Comment by jdsn** [comment]
next test run: https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/4295

**Comment by bmwiedemann** [comment]
:+1:  (though there should not be inactive networks, as the cleanup step should remove them first)

**Comment by dguitarbite** [comment]
Cleanup function does not do this yet, I will update it too. Thanks for pointing it out.

**Comment by dguitarbite** [comment]
@bmwiedemann Thanks for catching it. Removed the commit.

**Comment by dguitarbite** [comment]
Test passes: https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/4313/

**Comment by bmwiedemann** [comment]
:+1:

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
