### PR TITLE
Restore socok8s integration job (SOC-10434)

### PR DESCRIPTION
**Pull request by Itxaka**
Job was mistakenly deleted, restore it

### CODE REVIEW

**Comment by jsuchome** [comment]
If it was deleted, can't you revert the commit that did it?

**Comment by Itxaka** [comment]
> If it was deleted, can't you revert the commit that did it?

Not really, not without modifications to that commit, hence I rather have a new commit with just the restore. Lets not complicate it.

**Comment by JanZerebecki** [comment]
This is causing Jenkins to show an exception when visiting the jobs page and other subpages.
It started out beginning with `java.lang.ClassCastException: hudson.model.ParametersDefinitionProperty cannot be cast to com.cloudbees.hudson.plugins.folder.AbstractFolderProperty` and continuing as a normally long one.
Now it changed to just `java.lang.ClassCastException`, nothing more.

**Comment by JanZerebecki** [comment]
A similar problem happened in https://github.com/SUSE-Cloud/automation/pull/3433 .

**Pull request merged**
