### PR TITLE
fix boot order for lonely nodes

### PR DESCRIPTION
**Pull request by MaximilianMeister**
we want disk to be ordered after network in the default case
but ordered before in the lonely node case

### CODE REVIEW

**Comment by bmwiedemann** [comment]
:+1: code-wise - waiting for test to succeed

**Comment by rsalevsky** [comment]
codewise +1 but the commit message is not really understandable for people who are not so familiar with the code

**Comment by MaximilianMeister** [comment]
just changed the commit msg

**Comment by aspiers** [comment]
Please could we avoid using the term "lonely node"?  It's really unintuitive and doesn't at all match what it describes.

**Pull request merged**
