### PR TITLE
Lvcreate wrapper

### PR DESCRIPTION
**Pull request by jdsn**
1. drop transitioning code
2. use wrapper to create LVs to be able to handle VGs which have PVs of different sizes (otherwise they are limited to the size of the smallest PV).

### CODE REVIEW

**Comment by jdsn** [comment]
Successfully tested (creating LVs succeeded):
https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/4105/console

**Comment by jdsn** [comment]
Second successful testrun reported from Storage team.
Travis failuire is due to apt-get segfaulting.

**Comment by toabctl** [comment]
+1

**Comment by jdsn** [comment]
removed useless ${var} usage, otherwise no change in latest commit

**Comment by bmwiedemann** [comment]
:+1:

**Pull request merged**
