### PR TITLE
Power off extra nodes in a physical environment

### PR DESCRIPTION
**Pull request by dirkmueller**
when we run a scenario with less than the total number of nodes,
the extra nodes need to be powered down to not disturb the scenario.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
+1 - maybe mention that the "disturbing" comes from IPMI or other (admin/public) IP addrs conflicting with the newly given ones which causes random network trouble

**Comment by vmoravec** [comment]
+1

**Comment by jdsn** [comment]
:+1: with just some small nitpicking: all nodenumber variables follow the format "nodenumber<category>", so this would be: "nodenumnertotal" in this case

**Comment by dirkmueller** [comment]
@jdsn done

**Pull request merged**
