### PR TITLE
mkcloud: support calling steps with parameters

### PR DESCRIPTION
**Pull request by bmwiedemann**
Used like this:
mkcloud step1 step2 step3+paraA+paraB+paraC step4

This was added for cct tests but could be used for batch or others

### CODE REVIEW

**Comment by aspiers** [comment]
Nice idea to support parameters but it seems pretty hacky squashing multiple values into a single string - this could quickly get ugly if the values contain special characters or nested data structures.  Maybe it would make more sense to support a YAML file as input?

**Comment by bmwiedemann** [comment]
Then you would need to create and copy the yaml files to the right place, which would make it more fragile.
And of course you need this parameter mechanism to specify such a filename.

**Comment by MaximilianMeister** [comment]
LGTM

still not sure if it makes sense to integrate it at a point where we dont actually use it. but if we have use cases like crowbar_batch or cct that will use this mechanism then i am fine with integratin it now in advance

**Comment by aspiers** [comment]
> Then you would need to create and copy the yaml files to the right place, which would make it more fragile.

Why would that make it more fragile?

But anyway, I should have asked first: what parameters do you expect to be used?  Maybe they are all simple enough that YAML is overkill?  In the case of the `proposal` step, https://trello.com/c/ssI9nw9p will mean that you would only need one parameter, which is the path to the YAML file to use.  In that case we could get rid of *all* options which affect proposal attributes, and that would drastically simplify the existing code.  What do you think - does that make sense?

**Comment by aspiers** [comment]
> but if we have use cases like crowbar_batch or cct that will use this mechanism then i am fine with integratin it now in advance

Oh yeah good point, cct is another really nice use case!

**Pull request merged**
