### PR TITLE
Also deploy manila on Cloud 5

### PR DESCRIPTION
**Pull request by toabctl**
There's a Manila barclamp for Cloud 5 available. Deploy it.

### CODE REVIEW

**Comment by dirkmueller** [comment]
LGTM

**Comment by rsalevsky** [comment]
Somethings seams to be wrong with the barclamp, deployment fails.

**Comment by toabctl** [comment]
The package `crowbar-barclamp-manila` is not on the cloud 5 media. Fixed. Let's retest when a new media is ready.

**Comment by dirkmueller** [comment]
you also need to backport https://github.com/crowbar/crowbar/pull/2110 first

**Comment by toabctl** [comment]
> you also need to backport crowbar/crowbar#2110 first

PR for backport is here: https://github.com/crowbar/crowbar/pull/2132

**Comment by tboerger** [comment]
:+1:

**Comment by bmwiedemann** [comment]
test fails because there is still no manila installed

**Comment by bmwiedemann** [comment]
needs https://github.com/crowbar/crowbar/pull/2135

**Comment by toabctl** [comment]
And the barclamp only works with SLE12. So ```want_sles12=1``` is required

**Comment by toabctl** [comment]
Gating passed without ```want_sles12```. Testing with ```want_sles12=1``` now...

**Pull request merged**
