### PR TITLE
Test automation PRs against cloud 6

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by vuntz** [comment]
No strong feeling, just wondering: wasn't it discussed in the past? I recall something about it.

**Comment by dirkmueller** [comment]
yeah, but the discussion was inconclusive. there was only the action item to adam to figure out if it would make more sense to branch mkcloud/qa_crowbarsetup.sh . in that case switching master to develcloud6  is already a good change.

**Comment by jdsn** [comment]
In general, if you propose changes to the xml directly, please first rebase the respective job from the jenkins branch to get the latest changes in. This XML contains the wrong build node.

Thus: :-1:  for this PR
Anyhow the idea is ok.

**Comment by jdsn** [comment]
Btw. the proposed change is already in production. So we can just close this PR and only rebase the jenkins branch and we are fine.

**Pull request closed without merging**
