### PR TITLE
make DRBD database / rabbitmq LV size configurable

### PR DESCRIPTION
**Pull request by aspiers**

### CODE REVIEW

**Comment by jdsn** [comment]
This will conflict with https://github.com/SUSE-Cloud/automation/pull/287

**Comment by aspiers** [comment]
Yes I know but that's fine - whichever gets merged second will need a simple rebase and merge conflict resolution.

**Comment by aspiers** [comment]
@jdsn Rebased and conflicts fixed.

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
