### PR TITLE
chkconfig does not work on sle12+

### PR DESCRIPTION
**Pull request by MaximilianMeister**
replace it with systemctl

### CODE REVIEW

**Comment by bmwiedemann** [comment]
chkconfig is supposed to work on SLE12 - maybe it should be chkconfig libvirtd on ?

**Comment by aspiers** [comment]
Agree with @bmwiedemann, -1 as this should not be necessary if done right.

**Comment by MaximilianMeister** [comment]
so it then should be `chkconfig $service on`? we need to change it anyways

**Comment by bmwiedemann** [comment]
could you test this instead? https://github.com/bmwiedemann/automation/commit/a2e71ef455b53627f479de6c9ca7483be4bf37ec

**Comment by bmwiedemann** [comment]
merged

**Pull request closed without merging**
