### PR TITLE
Wait for backup step to finish

### PR DESCRIPTION
**Pull request by jsuchome**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
Is this how are customers supposed to do this?

**Comment by jsuchome** [comment]
Customers are supposed to check the status using the status command, but that's a little slower than checking the file directly, so we're doing it this way in mkcloud (see also other steps)

**Comment by bmwiedemann** [comment]
Maybe we still should use the status command, because we want to be sure it is working. And we do not care so much about performance there (a full run already takes 1-2 hours)

**Comment by jsuchome** [comment]
@bmwiedemann you have a point, I know, but let's just get this merged soon because it's needed for a rebuild of upgrade job.

I could add status checking with `crowbarctl upgrade status` later in a new PR.

**Pull request merged**
