### PR TITLE
Add a jenkins job for sle12sp2 testing

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by jsuchome** [comment]
Hm, we are about to remove `want_sles12sp2` in https://github.com/SUSE-Cloud/automation/pull/1033

**Comment by aplanas** [comment]
@jsuchome so that means that we jump the shark directly?

**Comment by jsuchome** [comment]
Well, https://github.com/SUSE-Cloud/automation/pull/1033 does not pass gating now, and once it does, it will tell us that SP2 as default works at least for default scenario. The question is however, when this can happen. Perhaps we can have `want_sles12sp2` until that time

**Comment by dirkmueller** [comment]
@jsuchome the whole point of the extra job is to highlight that it doesn't work.

**Comment by jsuchome** [comment]
(btw, my comment didn't mean -1, I was just hoping we could make the default switch instead)

**Pull request merged**
