### PR TITLE
removed obsolete nodenumbercompute

### PR DESCRIPTION
**Pull request by skazi0**
The parameter was not doing anything and the documentation was misleading.

### CODE REVIEW

**Comment by jsuchome** [comment]
@skazi0 have you thought about actually using the variable? (adapt the nova barclamp deployment code)

**Comment by skazi0** [comment]
@jsuchome no, because whole `mkcloud` uses calculated version of this variable (i.e. `numberofnodes - number_of_controllers_calculated_from_clusterconfig_or_default_of_1`)

**Comment by jsuchome** [comment]
Yeah, I mean that code would need to be changed. But it's probably not worth it.

**Comment by skazi0** [comment]
@jsuchome actually @jdsn is working on a new solution to node handling which will make some of this code obsolete but I wanted to clean this up as it was zero-effort and could save someone some time and confusion.

**Pull request merged**
