### PR TITLE
Mkcloud job name

### PR DESCRIPTION
**Pull request by jdsn**
Let the caller of an openstack-mkcloud run set the build name.
This allows shorter and more specific names and thus helps with the overview in job listings (and RSS feeds).

Will give this a test run tomorrow (initial test yesterday was successful).

### CODE REVIEW

**Comment by jdsn** [comment]
> My understanding was that everything got pushed to Jenkins from git, not the other way around, so why is this an exception?

answer for all except aspiers (SCNR): All JJB jobs (the ones in yaml) are pushed from git to jenkins. The remaining jobs (these that are in xml) are only backups of the jobs in jenkins.

This will go into the commit message so that @aspiers also finds it :)

**Comment by jdsn** [comment]
@aspiers 
Added a description to the commits that fetch resp. delete the xml based jenkins jobs. The commits are no longer part of this PR as it is a different topic to backup the jobs from jenkins. They are already comitted to master.

**Comment by jdsn** [comment]
I now take the liberty to merge this with only one +1000 :)
There is no other way to test this other than deploying it, and if it should be deployed, we need all parts, otherwise remaining parts will have the default "-no-name-" name.
Furthermore it makes sense to test this when not much happens (and thus not much can break) in jenkins - so many people being at the summit now is a good timeslot.

I will monitor it closely after the merge. If something fails for anybody - feel free to revert this PR entirely (without review, just revert).

**Comment by aspiers** [comment]
> This will go into the commit message so that @aspiers also finds it :)

I asked for it to go in the commit message not for *my* benefit, but so that *other* people could find it in years to come, when they are reading git history via `git log`, `git blame` etc. :stuck_out_tongue_closed_eyes:

But thanks for this great work!!

**Pull request merged**
