### PR TITLE
Deploy in CustomRegion again to test multi-region capability

### PR DESCRIPTION
**Pull request by dirkmueller**
Regression from the switch to crowbar_batch

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by jsuchome** [comment]
+1 What about other scenarios?

**Comment by aplanas** [comment]
+1

**Comment by dirkmueller** [comment]
@jsuchome which other scenarios? there is only one (the others are qa)

**Comment by jsuchome** [comment]
Yes, I meant QA ones, just in case they need it. But than QA would request it to be tested, so I assume we're fine there.

**Pull request merged**
