### PR TITLE
testing crowbar_register with mkcloud

### PR DESCRIPTION
**Pull request by MaximilianMeister**
We first setup n nodes to boot, and then register them with crowbar

### CODE REVIEW

**Comment by vuntz** [comment]
Nice; didn't review this in details, but it would be great if we add an option to pick between SLE11 and SLE12 for this. Or maybe this should depend on the want_sles12 flag?

**Comment by MaximilianMeister** [comment]
@vuntz sounds good. will have to tweak the implementation a bit

**Comment by bmwiedemann** [comment]
merged

**Comment by aspiers** [comment]
What is a lonely node?  There is no explanation anywhere in the commit messages or comments, and it's not obvious to me.

**Pull request closed without merging**
