### PR TITLE
Enable trove integration in rabbitmq

### PR DESCRIPTION
**Pull request by dirkmueller**
Since those batch files deploy trove, and trove checks whether
trove integration is enabled, deployment fails otherwise

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by bmwiedemann** [comment]
+1 on the code. In principle we could get away with a || return $? and let the runlist logic do the complaining, but this works too.

**Comment by toabctl** [comment]
+1

**Comment by bmwiedemann** [comment]
already merged, because test was not testing crowbar_batch anyway. We will see how it works for new jobs.

**Pull request merged**
