### PR TITLE
jjb: Remove Cloud 6 CD Jobs

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by dirkmueller** [comment]
@rsalevsky can you add a rationale? are the CD users switching to main cloud6?

**Comment by vuntz** [comment]
We still need CI for patches submitted to the sap-oc organization until May 2019; do you intend to replace this with something else?

**Comment by rsalevsky** [comment]
@vuntz Removing this has no impact on the PR gating for the sap-oc. This is just used for the Staging to non-Staging gating and as we close the CD channels this is not required going forward.

**Comment by dirkmueller** [comment]
@rsalevsky I meant rationale in the git commit message, not in this conversation (thanks!)

**Pull request merged**
