### PR TITLE
Remove CCT testsuite

### PR DESCRIPTION
**Pull request by rsalevsky**
We stoped using CCT since Cloud 8 and for older releases it creates
random failures. As nobody maintaines or fixes the tool let's remove it
as the value is limited.

### CODE REVIEW

**Comment by rsalevsky** [comment]
@aspiers This was decided over a year ago by the QE team during the Cloud 8 interlock preparations. The tools for testing are documented in the testing plan and CCT was specifically removed. I don't think this is the right time or place to restart the discussion as for me CCT is dead since Cloud 8. As this creates now random Cloud 7 tests I just do the necessary duty to remove it. Please remember the decision to stop using it was not taken by me.

**Comment by aspiers** [comment]
Exactly, thanks @jdsn.  Transparency is key for healthy team collaboration.

**Comment by rsalevsky** [comment]
I wrote a mail to the devel mailing list to clarify the situation.

**Comment by aspiers** [comment]
[**@rsalevsky**](https://github.com/rsalevsky) commented on [5 Oct 2018, 12:50 BST](https://github.com/SUSE-Cloud/automation/pull/2831#issuecomment-427338924 "2018-10-05T11:50:19Z - Replied by Github Reply Comments"):
> I wrote a mail to the devel mailing list to clarify the situation.

Thanks a lot for doing that!  I replied there - would be good to get a bit more clarity around the team's position and strategy regarding BDD before we progress on this PR.

**Comment by aspiers** [comment]
@jdsn I'm not sure but I think #2838 already achieved the effect of 1.  @rsalevsky can you confirm?  What about for C8?  Although yes, removing it from the default step expansions would be a more intuitive approach.

Regarding 2. I think this would be a mistake given that people have already stated on the mailing list that they are still using it.

**Comment by jdsn** [comment]
@aspiers yes, https://github.com/SUSE-Cloud/automation/pull/2838 solves the 1st issue, but its kind of hidden, because cct is still there and the step will be executed but then do nothing because the ISO is not defined.
So yes, I also would have preferred the removal from the step lists. But its solved for now.

Regarding 2. I agree, that would have been the subject of the discussion in the new PR. But we could have decided on both topics individually without blocking the CI.

@rsalevsky 
I think we can close this PR for now as the issue is solved differently.
Feel free to rebase, change, split, ... after the discussion on the mailinglist.

**Pull request closed without merging**
