### PR TITLE
Rename forceneutronsles12 to want_neutronsles12.

### PR DESCRIPTION
**Pull request by aplanas**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
could you please add this option as a comment to the [undocumented options](https://github.com/SUSE-Cloud/automation/blob/master/scripts/mkcloud#L70)?

relates to the issue https://github.com/SUSE-Cloud/automation/issues/256

**Comment by aplanas** [comment]
@MaximilianMeister I added the variable and I ordered the list for a more easy reading.

**Comment by MaximilianMeister** [comment]
:+1:  thanks

**Comment by aspiers** [comment]
So -1 as it stands, but it should only take a few minutes to make the suggested changes and convert that into a +1 :)

**Comment by jsuchome** [comment]
+1

**Comment by aplanas** [comment]
Separate the last commit in two commits

**Comment by aspiers** [comment]
Sorry, still -1.  It should add documentation rather than expand an existing TODO list.  Also would prefer not to alphabetically sort the options since they are currently grouped logically which is more useful.

**Comment by aplanas** [comment]
* Remove the commit that order the undocumented variables.
* Document want_neutronsles12 variable.

r? @aspiers

**Comment by aspiers** [comment]
+1! :)

**Pull request merged**
