### PR TITLE
Switching jobs to use lightweight checkout

### PR DESCRIPTION
**Pull request by gosipyan**
After recent Jenkins security updates all CI pipeline jobs start to
fail. Adding work around by enabling lightweight checkout.

### CODE REVIEW

**Comment by gosipyan** [comment]
Tested with https://ci.suse.de/view/Cloud/view/1)%20Cloud%20Gating/job/cloud-8-gating/

**Review by JanZerebecki — APPROVED** [review]
This will break testing them on PRs. Do you have a link to the bug that prevents passing the repo url/branch from a variable?

**Comment by gosipyan** [comment]
@JanZerebecki there are several issues https://issues.jenkins.io/browse/JENKINS-62019 one of them .

**Review by skazi0 — APPROVED** [review]
lgtm

**Comment by gosipyan** [comment]
@JanZerebecki  which jobs would break if this is merged ? Maybe there is solution merge this without breaking anything .

**Comment by JanZerebecki** [comment]
How do you run a job on a PR if the argument for a different branch doesn't work? I don't know of a way to not break that. And its broken either way as without this change the jobs don't work either.

**Comment by gosipyan** [comment]
Looks like issue got fixed on CI side and no need this workaround thanks for reviews .

**Pull request closed without merging**
