### PR TITLE
Make devstack CI job work again

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by dirkmueller** [comment]
@toabctl the ca-certificates one is debateable. imho this should rather be done in the base image. any opinion?

**Comment by bmwiedemann** [comment]
then it would only work with certain base images... IMHO tom's way is nicer

**Comment by toabctl** [comment]
@bmwiedemann which way?

**Comment by bmwiedemann** [comment]
err, dirk wrote it. I meant installing the required packages with zypper - this way you can re-use one minimalistic base image for all kinds of jobs.

**Comment by dirkmueller** [comment]
@bmwiedemann the point is that the image is insecure by default without including the trusted root CAs.

**Pull request merged**
