### PR TITLE
support for generic proposal skip

### PR DESCRIPTION
**Pull request by jdsn**
in order to move the manila test to a dedicated job we need to support the want_manila switch

### CODE REVIEW

**Comment by jsuchome** [comment]
+1

**Comment by MaximilianMeister** [comment]
+1

**Comment by toabctl** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by toabctl** [comment]
CI failed with ```Error: Waiting for 'node d52-54-77-77-77-02.vd3.cloud.suse.de' timed out.```. Rechecking ...

**Comment by dirkmueller** [comment]
@jdsn but this doesn't deploy manila at all anymore.. that doesn't make sense. we should skip the manila *testing* in cct.

**Comment by jdsn** [comment]
> @jdsn but this doesn't deploy manila at all anymore.. that doesn't make sense. we should skip the manila testing in cct. 

That what Rick created the new manila test for:  https://github.com/SUSE-Cloud/automation/pull/927
The goal is to separate the builds to make the regular runs faster and to make it visible when manila is really broken and when a gating fails because of its gating (and not because of a manila issue).

**Comment by dirkmueller** [comment]
https://github.com/jdsn/SUSE-Cloud--automation/blob/support-for-want_manila-switch/scripts/qa_crowbarsetup.sh#L4199

**Comment by toabctl** [comment]
This doesn't work. cct will execute the manila client tests. And it will fail if manila is not deployed.

**Comment by dirkmueller** [comment]
ah, you mean tempest?

**Comment by dirkmueller** [comment]
I thought the cct tests are the issue.. so we should skip those and not remove manila alltogether..

**Comment by dirkmueller** [comment]
@jdsn I'm aware of the other PR, thanks

**Comment by jdsn** [comment]
> I thought the cct tests are the issue.. so we should skip those and not remove manila alltogether..

Not its about failures in the deployment of manila.
And its not removed alltogether, but moved to a dedicated job.

**Comment by dirkmueller** [comment]
@jdsn you're removing it from the PR gating..

**Comment by toabctl** [comment]
> The goal is to separate the builds to make the regular runs faster and to make it visible when manila is really broken and when a gating fails because of its gating (and not because of a manila issue).

Again - it's usually not Manila that is broken but the other components (nova, cinder, not enough ram on the compute nodes, ...). Manila just uses a VM and triggers failures. So removing Manila means not catching theses errors early. But I'm fine with moving it to gate if there's an agreement todo that.

**Comment by jdsn** [comment]
closed this PR as the scope changed after a discussion - so reviews dont count anymore

@jsuchome @MaximilianMeister @toabctl @rsalevsky @dirkmueller 
please review https://github.com/SUSE-Cloud/automation/pull/926  instead

**Pull request closed without merging**
