### PR TITLE
Synchronize ci.suse.de jobs with japi fetch-all

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by aspiers** [comment]
Does this mean people have been bypassing this git repo and changing the config on the server directly?  I thought we wanted to avoid that, but it's very likely I'm misunderstanding something ...

**Comment by jdsn** [comment]
@aspiers Changing the jobs only in XML is cumbersome. We ususally change via webUI and then commit the changes to git. So the git repo is just the backup.

**Comment by jdsn** [comment]
Well I backup the jobs to our internal backup as well. So this is kind of duplication. But it makes the jobs public (which our internal backups are not, obviously). Maybe we need to rethink this topic again.

**Comment by aspiers** [comment]
OK I see, thanks for the info.  Looks like [`scripts/jenkins/ci.suse.de/cloud-mkcloud5-ovsvxlan-trigger.xml`](https://github.com/SUSE-Cloud/automation/pull/267/files#diff-8804714f1600abe04c7661afb0ee33d7) was the added trigger required by [the story for adding VXLAN support](https://trello.com/c/9iwlyCET).

**Comment by jdsn** [comment]
So :+1: 
But I think it would be better in the long run to have an automated machanism, that fetches the jobs and in case of changes puts them into a git repo (not necessarily this one, but we should include the job history of this repo).

**Comment by toabctl** [comment]
Just for the record: There is jenkins-job-builder (https://pypi.python.org/pypi/jenkins-job-builder/1.1.0) which is used by openstack to define the jenkins jobs. it uses yaml for that. Seems to be a good alternative to the xml format.

**Comment by jdsn** [comment]
Thanks for the link. We stopped building jobs via scripts a while ago (all trigger jobs for cloud 1 and 2 were generated). Anyhow I hope that we maintain and improve our infrastructure and CI setup in a way that we do not need a jenkins job creator in the first place.

**Pull request merged**
