### PR TITLE
Remove Cloud 6 CD from trackupstream

### PR DESCRIPTION
**Pull request by rsalevsky**
We deleted the gating job for this some time ago so this is more or less
usefull.

### CODE REVIEW

**Comment by vuntz** [comment]
Hrm, won't this remove the ability to test this branch with the latest code?

**Comment by rsalevsky** [comment]
It would but we don't run any CI jobs for this any longer so not sure who is testing the code? As a general remark it seams to me that the CI and testing around Cloud 6 doesn't make sense in the current way.

**Comment by vuntz** [comment]
The problem is that we're maintaining Cloud 6 CD for one additional year (at least), so removing all the infrastructure for it is going to hit us at some point. We should really not do that.

If there's an issue with keeping the CI alive for this, this is something to put on the menu for the SAP squad.

**Comment by rsalevsky** [comment]
@vuntz Agreed, the issue I'm seeing right now that we are in an inconsistent state. We have CI for Cloud 6 but not for Cloud 6 CD. We should decide which flavor we keep alive (Cloud 6 vs. Cloud 6 CD) and then switch the CI to only track this. AFAIK only one flavor is used anyway.

**Comment by vuntz** [comment]
@rsalevsky unless I'm mistaken, Cloud 6 is EOL, and we have LTSS only for the CD branch. If correct, then choosing to keeping the CD branch alive is definitely the right thing to do.

**Pull request closed without merging**
