### PR TITLE
jenkins/mkcloud/ha: enable ssl for all services

### PR DESCRIPTION
**Pull request by bmwiedemann**
enable ssl for all services
in order to be closer to our required production cloud setup.
    
still missing:
controller_raid_volumes=2
want_ldap=1

### CODE REVIEW

**Comment by vuntz** [comment]
Why don't we enable it in the non-ha scenario first? The ha scenario may fail for tons of reasons already, and it feels more productive to first make sure ssl always works before adding more failures to the ha job.

**Comment by bmwiedemann** [comment]
@vuntz we have
https://ci.suse.de/view/Cloud/view/Cloud5/job/cloud-mkcloud5-ssl-trigger/
https://ci.suse.de/view/Cloud/view/Cloud6/job/cloud-mkcloud6-job-ssl-x86_64/
https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-ssl-x86_64/
and they are even sometimes green

**Comment by bmwiedemann** [comment]
> are you sure we want to fix it everywhere
someone told me, 'we should do HA for cloud.suse.de because everyone is using HA and SSL in production'
so I guess, we want to fix all of these issues. Maybe not in the gate atm.

**Comment by jdsn** [comment]
So then it might be a better option to change the dedicated ssl jobs (see comment 2) to be HA, and keep the gatings (even the HA ones) without ssl - at some point in the future we could switch

**Comment by dirkmueller** [comment]
@bmwiedemann I didn't say everyone uses HA+ssl. I only said that those who use ssl most likely also use HA, so it makes sense to have those tested together. And it would allow ssl termination at haproxy which would somewhat simplify our cookbooks.

**Comment by jdsn** [comment]
@bmwiedemann @dirkmueller 
What is the outcome here? Do we need/want a change? Adapt this PR? A different solution?

No update since April - lets find a solution or close this PR.

**Comment by dirkmueller** [comment]
@jdsn imho this can be closed, the -vproduction- scenario covers this usecase now.

**Pull request closed without merging**
