### PR TITLE
Fix PR testing for barclamp-crowbar again

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by vuntz** [comment]
Did you really want all these commits, or just the last one?

**Comment by dirkmueller** [comment]
@vuntz all. we can split it into two PRs if you want though..

**Comment by vuntz** [comment]
@dirkmueller was just unsure if it was wanted, hence the question

+1

**Comment by toabctl** [comment]
+1

**Comment by bmwiedemann** [comment]
:+1:

**Pull request merged**
