### PR TITLE
Move all Cloud 6 triggers to jjb and "cloud-mkcloud6-foo-trigger" naming convention

### PR DESCRIPTION
**Pull request by vuntz**
Note that I have not run jenkins-jobs yet to update jenkins; I'll do that only once we have agreement on the naming convention.

I'll also only delete the old triggers/jobs if we're fine -- otherwise, I'll just rename and disable them.

### CODE REVIEW

**Comment by vuntz** [comment]
Btw, I kept the same timed triggers. Whether they make sense or not, that's another story...

**Comment by dirkmueller** [comment]
I kind of liked not having the -trigger suffix anymore. with the move of them being a blocking job with correct weather report, I wouldn't call them trigger. (trigger was something iirc so that you can filter it because the weather report and build status was not interesting)

**Comment by vuntz** [comment]
@dirkmueller I'm fine with another naming convention as long as we only have one convention :-) The "-trigger" one was suggested by @jdsn.

@jdsn: are you fine if we move to "-job-" instead?

This leaves the question of what to do for the gating ones? Do we call them triggers or jobs?

**Comment by vuntz** [comment]
Changed to "-job-" naming convention.

**Comment by toabctl** [comment]
I'm fine with the current naming. But in general we could use a job template to simplify things. But for now, +1

**Comment by jdsn** [comment]
@dirkmueller @vuntz @toabctl The point of the suffix is not necessarily the filtering. It should also make it clear what job actually 'does' something and what job is just calling another one in order to show a status. These jobs that do nothing should also be running on the 'cloud-trigger' node, in order not to block an executor on a real worker.
IMHO a suffix (whatever it is called, but consistently used though) makes a lot of sense to easily see the difference. This also helps when creating such new jobs.
Additionally it is a lot easier to grep for trigger-jobs that are not configured to be run on the cloud-trigger node (or the other way round).

So change the suffix to whatever you like (trigger, caller, monitor, ... ), as long as it is not an empty string and it is used consistently. I am against dropping the suffix for the sake of dropping it.

**Comment by jdsn** [comment]
> Changed to "-job-" naming convention.

@vuntz now I got it, the proposal is to use "-job-" as an *infix*, instead of a *suffix*.
Well this would make it possible to grep and filter. But from my point of view the term "job" is too generic to make the difference obvious (everything in jenkins is a job) and it hides in the middle.

As an *infix* the term needs to be more precise, IMHO.

**Comment by vuntz** [comment]
Would we be fine using "scenario" as infix/suffix/prefix/whatever-we-want? (I actually prefer avoiding a suffix because it makes quick parsing of the report page harder)

Something like either cloud-mkcloud6-scenario-xen, or cloud-scenario-mkcloud6-xen.

**Comment by vuntz** [comment]
Or second proposal: do we really need something? Isn't "cloud-mkcloud6" good enough?

**Comment by dirkmueller** [comment]
@vuntz we didn't want to name it "scenario" because that is a QA defined term (e.g. scenario 2a) and we wouldn't want to overload it with a different name. 

I also hate the suffix because it makes parsing hard. I prefer the "-job-" prefix because it makes things, when sorting alphabetically, appear close together which improves overview. 

I'd just call it -job- when it deploys a specific "scenario" with mkcloud".

**Comment by dirkmueller** [comment]
+1 (although maybe some of the commits could be squashed)

**Comment by jdsn** [comment]
:+1: but feel free to squash

I will adapt the jenkins view accordingly.

**Pull request merged**
