### PR TITLE
Remove swift attributes for trove

### PR DESCRIPTION
**Pull request by vmoravec**
and add empty lines between sections for better visual parsing.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
Would be nicer if you split the whitespace change into a separate commit. You can still do that using
```bash 
git reset --patch HEAD^
git commit --amend
git commit -a
```

**Comment by aplanas** [comment]
I agree with @bmwiedemann

**Comment by vmoravec** [comment]
@bmwiedemann @aplanas Whitespace cleanup and fix for trove moved into separate commits.

**Comment by aplanas** [comment]
+1

**Comment by vmoravec** [comment]
Rebased due to conflicts

**Comment by bmwiedemann** [comment]
the change needs a commit message answering the Why

**Comment by vmoravec** [comment]
Commit message improved

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
