### PR TITLE
add checks for inconsistencies in OBS projects

### PR DESCRIPTION
**Pull request by JanZerebecki**
Checks the packages in SOC projects for consistency (see
ObsStatusCloud.diff_projects() for details) and diffs the packages as they pass
these projects, lists those with changes and checks the diff for a few errors
(see ObsStatusCloud.rdiff_packages_devel() for details).

### CODE REVIEW

**Comment by JanZerebecki** [comment]
This was mentioned in https://jira.suse.com/browse/SOC-11034

**Comment by JanZerebecki** [comment]
I used this to find and fix a few errors, like packages that changed in the product, but not in devel nor obs. Every now and then errors like these caused problems for us.

**Comment by jgrassler** [comment]
Looks good at first glance, but I've got a couple of ideas, still (no need to go and implement them straight away let's get a discussion going):

First, I'm not 100% sure about the static lists of packages `in_product_but_not_in_devel` . That introduces yet another source of truth for where packages should and shouldn't be, that will need to be updated if changes happen. I.e. if somebody adds a staging link for a package where that actually makes sense, that will require either a change to this script or cause needless spam. How about forming the intersection of the packages between OBS, IBS Staging, IBS Non-Staging and product projects every time the script runs and outputting a warning about any package that's in the complement of that intersection? One could even introduce a command line option so that check isn't run every time (people might not be interested in that option most of the time. Differences between packages that shouldn't differ are probably the most interesting information, to most.

Second, and somewhat related: we could try and attempt to answer the ever-popular questions of "What's the most downstream project/OpenStack project (in the case of rpm-packaging) I need to submit my change to?" and "At what points further upstream will I have to create a manual submitrequest (e.g. when a package is in OBS but not in IBS staging)?". That could be automated based on the information about the exact whereabouts of a package you are gathering in your script and a few extra criteria that are easily determined (e.g. "Does the package have a _service file with the renderspec source service configured?").

**Comment by JanZerebecki** [comment]
The "where to submit"-feature is a good idea. Though part of that would pain me.

In the same way having expected differences of the list of packages in projects pains me. I'd prefer to just have all the packages uniformly follow the same rules. But I don't know if fixing this in a product that was released so long ago is worth it.

> I.e. if somebody adds a staging link for a package where that actually makes sense, that will require either a change to this script

Just adding a staging link doesn't if the package is already in devel and the product. But for other cases it would, like adding a package in obs that is only in the product.

> How about forming the intersection of the packages between OBS, IBS Staging, IBS Non-Staging and product projects every time the script runs and outputting a warning about any package that's in the complement of that intersection?

I don't think that helps much as that would warn about packages that are not in staging but in non-staging. Unless we add every package in staging. But otherwise it pretty much does that.

> One could even introduce a command line option so that check isn't run every time (people might not be interested in that option most of the time.

Maybe I should put it in a different job, but it is not much work as most of the same information from OBS/IBS is needed for diffing the packages anyway, so I left it in for now.

I'll disable failing the job by any unexpected differences in the list of packages in projects. Does that address your concern?

**Review by jgrassler — APPROVED** [review]

**Comment by JanZerebecki** [comment]
Please re-approve. Missed a space at the beginning of the comment to make flake8 happy.

**Review by jgrassler — APPROVED** [review]

**Comment by JanZerebecki** [comment]
I found https://github.com/SUSE-Cloud/automation/pull/3780 which is also looking at changed packages, I'd suggest merging both PRs, to merge the functionality in follow up PRs.

**Review by rtamalin — APPROVED** [review]
I have looked at this in the past and it looks reasonable but I can't say I 100% grok all that it is doing ;-)

However so long as it doesn't fail things for the unexpecteds, I guess we should get it in.

**Pull request merged**
