### PR TITLE
Switch off lbaasv2 for cloud-mkcloud7-job-magnum-x86_64 CI Jenkins

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by mjura** [comment]
With merging please wait for want_magnum gating tests

**Comment by mjura** [comment]
It depends on https://github.com/crowbar/crowbar-openstack/pull/583

**Comment by toabctl** [comment]
@mjura can you explain (in the commit msg) **why** you want to switch it off?

**Comment by toabctl** [comment]
lbaasv1 is deprecated and already removed in Newton.

**Comment by mjura** [comment]
@toabctl : I've added comments to commit message. I know that lbaasv1 is deprecated for Newton, I already created card about adding support for Magnum driver for lbaasv2. I will drop this change when we will switch for Newton in develcloud7

**Comment by dirkmueller** [comment]
since we switched to newton, this change shouldn't be needed.

**Pull request closed without merging**
