### PR TITLE
added CLOUDSLE12TESTISO to GM6 cloudsource case

### PR DESCRIPTION
**Pull request by tpatzig**

### CODE REVIEW

**Comment by dirkmueller** [comment]
@tpatzig can you explain the rationale of this change? I think we need to test whether that has a chance of succeeding. Right now the content of cloud testing media isn't really used that much.. is there a specific reason on why want that change?

**Comment by tpatzig** [comment]
@dirkmueller no specific reason. The TESTISO was just defined for develcloud6 and it worked fine (rsync from iso, install test packages) we switched over to GM6+up and saw this error

https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L4420

and its also defined for GM7. If it is not used, we should remove it, but for all cloudsources.

**Comment by jdsn** [comment]
I agree with @tpatzig that it makes sense to keep it for consistency, so it can be used later.

**Comment by jdsn** [comment]
The alternative https://github.com/SUSE-Cloud/automation/pull/1941 is already merged. Thus closing this PR now.

**Pull request closed without merging**
