### PR TITLE
Do not skip patches that are interactive

### PR DESCRIPTION
**Pull request by jsuchome**
Currently our 'runupdate' step ignores the kernel update.

### CODE REVIEW

**Comment by jdsn** [comment]
A hint why this change is needd should be added to the commit and/or the code.
The description of this PR might be lost.

**Comment by jsuchome** [comment]
@bmwiedemann I've seen you commenting on https://github.com/SUSE-Cloud/automation/pull/1438 which was already merged and included patch from this PR.

First, it wasn't necessary for upgrade only, I think we should not ingore patches during the runupdate step in general. But if you disagree, I can revert the patch and prepare some solution that is only upgrade specific

**Comment by jdsn** [comment]
> But if you disagree

@jsuchome Thats not the point. A short explanation about **why** this change is needed was missing. What issue gets solved by this change.

If no hint is not provided the change will $somewhen be reverted like PR #1446 

So maybe add the "why" with this PR.

**Comment by jsuchome** [comment]
@jdsn the commit was already merged (so this PR is actually obsolete) Do you want me to create PR which just adds a comment and proper commit message?

**Comment by dirkmueller** [comment]
@jsuchome why do you want to install a kernel update? that basically means that if there is a kernel update over the prebuilt image, the rest will just fail (it might reference no longer installed kernel modules or install kmps that are not matching the currently running kernel).

**Comment by jsuchome** [comment]
@dirkmueller the original reason was to have all updates present before we start the upgrade. And I've added it here (to `zypper_patch`) because I did not see a reason to _NOT_ install kernel updates in `runupdate` step.

But again: this is already merged as it was part of https://github.com/SUSE-Cloud/automation/pull/1438. I assume you want me to revert this commit now, right?

**Comment by jsuchome** [comment]
Closing this one, as the change was already merged. See revert here https://github.com/SUSE-Cloud/automation/pull/1453

**Comment by bmwiedemann** [comment]
btw: just installing a kernel update does not make a difference (except for causing potential breaking in kmp deps), because the new kernel is only active after a reboot and for updates within service-packs there is no change in functionality anyway.

**Pull request closed without merging**
