### PR TITLE
Switch deprecated nova commands to openstack

### PR DESCRIPTION
**Pull request by s-t-e-v-e-n-k**
nova floating-ip-create is deprecated, and will soon be removed, switch
to using neutron floatingip-create.

### CODE REVIEW

**Comment by kbaikov** [comment]
Isn't there some openstack cli equivalent?

**Comment by s-t-e-v-e-n-k** [comment]
Sure, I can switch to using the openstack command instead.

**Comment by kbaikov** [comment]
That would be cool.

**Comment by dirkmueller** [comment]
@s-t-e-v-e-n-k this needs extra handling for cloud5 .. I think the new calls only work for cloud7

**Comment by s-t-e-v-e-n-k** [comment]
@dirkmueller I *think* it will be fine for Cloud 6, but I'm not certain. I will toss this change at both Cloud 5 and 6 and report back.

**Comment by s-t-e-v-e-n-k** [comment]
I clearly no longer have time to work on this.

**Pull request closed without merging**
