### PR TITLE
Backup restore cloud 6

### PR DESCRIPTION
**Pull request by jdsn**
Adds backup and restore for Cloud6.
This will allow to test the functionality of the upgrade process earlier (upgrade will folllow as part or PR #716 ).

### CODE REVIEW

**Comment by bmwiedemann** [comment]
+1 on the code... just needs to pass a cloud backup+restore for cloud5 and cloud6

**Comment by MaximilianMeister** [comment]
+1

**Comment by jdsn** [comment]
Cloud6 testing successful
manually addded status
rerunning test with Cloud5

**Comment by bmwiedemann** [comment]
cloud5 test successful in https://ci.suse.de/job/openstack-mkcloud/15427/ though it didnt have a "testsetup" step after the restore, so we dont know if the restore actually worked.

**Comment by toabctl** [comment]
Is this ready to me merged?

**Comment by jdsn** [comment]
@toabctl nope, not yet, tests were still failing
I did a force push now and retrigger the tests.

**Pull request merged**
