### PR TITLE
revert mkcloud: workaround vlan/virtio checksum offloading bug

### PR DESCRIPTION
**Pull request by bmwiedemann**
revert 2029b683
https://bugzilla.novell.com/show_bug.cgi?id=884706
as it is probably fixed by now

### CODE REVIEW

**Comment by nicolasbock** [comment]
Is this bug you reference fixed now?

**Comment by bmwiedemann** [comment]
We dont know. The point of this PR is to find out. Triggered by discussion in
https://bugzilla.suse.com/show_bug.cgi?id=1015266

**Comment by dirkmueller** [comment]
@bmwiedemann I guess you have to explicitely enable it then to really find out?

**Comment by bmwiedemann** [comment]
@dirkmueller no, the bridge is newly created by libvirt with offloading default on
```
# ethtool -k vl3br | grep tx-check
tx-checksumming: on
```

**Comment by aplanas** [comment]
I would add the bsc# in the title and write more background...

**Comment by dirkmueller** [comment]
ideally we'd have a clear version check for the kernel here (>= 4.4 and let it disabled for older incarnations)

**Comment by bmwiedemann** [comment]
bug was for SLE-12 and I had found SP1 to be fixed a year ago... but they share the 3.12 kernel version and SLE-12-GA is EOL anyway and we dont run it anywhere anymore... so should be good.

**Comment by dirkmueller** [comment]
@bmwiedemann I remember you said its still an issue on SLE11 kernels. are you saying it was fixed there as well?

**Comment by bmwiedemann** [comment]
The bug only appeared when we started to use SLES12 hosts with new 'vhost' code path in libvirt+kvm so probably is not in SLE11*

**Pull request merged**
