### PR TITLE
Fix duplicate usage of nvram

### PR DESCRIPTION
**Pull request by dirkmueller**
We need to use a node-specific file

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
Ah, you need to fix the test suite, though.

**Comment by toabctl** [comment]
Tests still failing with ```KeyError: 'nodecounter_VARS'```

**Comment by bmwiedemann** [comment]
+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
