### PR TITLE
mkcloud: allow to call onadmin function

### PR DESCRIPTION
**Pull request by bmwiedemann**
this allows to add new functions to qa_crowbarsetup
that can be called through mkcloud as
onadmin+funcname
or even
onadmin+func+param1+param2

### CODE REVIEW

**Comment by aspiers** [comment]
Not a -1, but why do we need this?

**Comment by bmwiedemann** [comment]
it would help getting rid of the many mkcloud functions that do nothing else than call a onadmin
e.g. proposal, cloudupgrade*, cct, setup_aliases, batch

**Comment by aspiers** [comment]
But then wouldn't we have to type 

    mkcloud ... onadmin+setup_aliases onadmin+proposal onadmin+cct

?  That's really ugly and inconvenient.

**Comment by bmwiedemann** [comment]
On the positive side it would be more explicit. But we could use aliases to still allow calling it the old way.

**Comment by jdsn** [comment]
> But then wouldn't we have to type
>  `mkcloud ... onadmin+setup_aliases onadmin+proposal onadmin+cct`
> ? That's really ugly and inconvenient.

No, you wouldn't have to. But this PR would allow for it  :)
I agree that it is ugly and inconvenient.

So the PROs are
- no need to declate new qa_crowbarsetup functions in mkcloud, they will just be accessible via onadmin
- using onadmin+$something makes it obvious where the code is to be run, transparency

The CONs:
- ugly, inconvenient
- more to write (if used manually and incrementally - you could stil use aliases)

Anything else? @aspiers @bmwiedemann 

IMHO we should use the opportunity and discuss this PR and yours, @aspiers, that adds more (sub)aliases (https://github.com/SUSE-Cloud/automation/pull/323) and try to find a better approach to deal with all this. I'd like to see a proposal that combines the PROs of both PRs (and maybe more) but leaves out the CONs.

Let's try to find something that we all can agree to.

**Comment by aspiers** [comment]
I'm not convinced about the transparency "PRO"; I can't think of any steps which currently use `onadmin` and for which it's not already obvious that they run on the admin node.

Having said that, I can't think of any significant disadvantage to doing this - even though I don't personally see much advantage I won't give a -1.

But yes I think it's time to have a mumble discussion about steps in general, as per #323.   Maybe next week?

**Pull request merged**
