### PR TITLE
No role nova-multi-compute-lxc exists

### PR DESCRIPTION
**Pull request by mmnelemane**
Fix for https://ci.suse.de/job/openstack-mkcloud/28799/console

### CODE REVIEW

**Comment by nicolasbock** [comment]
@vuntz removed the `multi` roles in https://github.com/crowbar/crowbar-openstack/commit/585042764968c548a2cf52e4eb4c1804df7683ef. Could you verify potential changes regarding the other compute backends and that we might not have to change https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L85 and remove the `multi` part, i.e. remove the `6plus` conditional?

**Comment by mmnelemane** [comment]
@nicolasbock: The problem is that no role is created for "lxc" (with or without `multi`)

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
https://github.com/SUSE-Cloud/automation/pull/1108 is an alternative..

**Comment by dirkmueller** [comment]
lets merge this as it passes gating and got reviews..

+1

**Pull request merged**
