### PR TITLE
ironic: port cloud7 scenario fixes to cloud8

### PR DESCRIPTION
**Pull request by skazi0**
Cloud8 ironic scenario was copied before original Cloud7 version was
fully working. Bug fixes from Cloud7 are ported co Cloud8 here.

Port of #1979 and #1976 to Cloud8.

### CODE REVIEW

**Comment by skazi0** [comment]
I (re)sarted the job that this PR is supposed to fix with the PR as parameter.

**Comment by skazi0** [comment]
rebased

**Comment by skazi0** [comment]
@jsuchome ironic gating finally succeeded :)

**Comment by jsuchome** [comment]
cool!

**Pull request merged**
