### PR TITLE
allow user inject own public keyfile in preparecrowbar

### PR DESCRIPTION
**Pull request by mimi1vx**
add ability to inject user own public key

### CODE REVIEW

**Comment by aspiers** [comment]
Great idea to add this feature (in fact I was just wishing for exactly the same thing earlier today!) but I have to give -1 until two problems are addressed:

1. Travis fails the bashate check due to trailing whitespace
2. By adding yet another undocumented option, you are increasing technical debt.  This should never happen!  Please document the option properly.  (See also #256)

**Comment by mimi1vx** [comment]
@aspiers  better ? trailing whitespace removed + add small docu.

**Comment by aspiers** [comment]
Yes that's better - thanks a lot!  Although now I'm wondering why we need to append *both* `$keyfile` *and* `$user_keyfile`.  As this PR currently stands, `$user_keyfile` is more useful because it lets you choose which file is appended, whereas `$keyfile` is hardcoded to `~/.ssh/id_dsa.pub` (where `~` means `/root` since `mkcloud` needs to run as `root`).  But it would also be easy to parametrize `$keyfile`.  What do you think?

**Comment by mimi1vx** [comment]
not good idea, roots public key is needed in all steps after setupadmin

**Comment by aspiers** [comment]
Ah of course!  In that case +1 from me.

**Comment by MaximilianMeister** [comment]
:+1:

**Pull request merged**
