### PR TITLE
qa_crowbarsetup: Use different branch for SES testing

### PR DESCRIPTION
**Pull request by toabctl**
The storage team uses the "storage3" branch for SES3 and SES4 testing.

### CODE REVIEW

**Comment by toabctl** [comment]
This will still fail but that seems to be a problem with the storage testing itself.

**Comment by toabctl** [comment]
Related: https://gitlab.suse.de/ceph/qa-automation/merge_requests/21

**Comment by toabctl** [comment]
So there is a version mismatch for SES4 currently. Will be fixed by the SES team. Then the tests should pass

**Comment by toabctl** [comment]
> So there is a version mismatch for SES4 currently. Will be fixed by the SES team. Then the tests should pass

according to IRC, the fix will be in the SES4 iso tomorrow.

**Comment by aspiers** [comment]
This broke the ceph sanity test suite - attempted workaround is in #1395.

**Comment by aspiers** [comment]
But if we'd had [#stableCI multiple configs for Crowbar repo PR gates (Trello)](https://trello.com/c/IcWmgI8E/30-8-stableci-multiple-configs-for-crowbar-repo-pr-gates), the CI would have found the breakage for us ...

**Pull request merged**
