### PR TITLE
Fix jenkins mkcloud

### PR DESCRIPTION
**Pull request by bmwiedemann**

### CODE REVIEW

**Comment by jdsn** [comment]
:-1: the job XMLs are here as a backup, please do not add them into a PR

**Comment by jdsn** [comment]
just change the jobs via GUI

**Comment by bmwiedemann** [comment]
I _did_ change the jobs via GUI and this _is_ the backup

**Comment by jdsn** [comment]
then drop the backup commit from the PR

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
