### PR TITLE
qa_crowbarsetup: Wait longer for volume detach/attach

### PR DESCRIPTION
**Pull request by toabctl**
The basic test to attach a volume, create a fs, write something detach it
and attach it again needs some more time to not error out.
Use the already available "wait_for" function to check for the current
volume state before doing the next step.

### CODE REVIEW

**Comment by toabctl** [comment]
FYI: The problem seems to happen i.e. in https://ci.suse.de/job/openstack-mkcloud/8127/consoleFull . After reattaching the device and checking some file content on the fs, the error is: ```16:00:23 mount: special device /dev/vdb does not exist```

**Comment by vuntz** [comment]
+1

**Comment by toabctl** [comment]
Just rebased, no changes done.

**Comment by vuntz** [comment]
Still +1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
