### PR TITLE
Remove hack to add cloud repos to SP1 directory

### PR DESCRIPTION
**Pull request by rhafer**
With the switch to SP2 this shouldn't be needed anymore.

### CODE REVIEW

**Comment by rhafer** [comment]
This should fix the current failures when installing SES nodes (still SP1 based).

I still need to verify that this doesn't cause new issues.

**Comment by rhafer** [comment]
This seems to work (at least better than before). I could deploy a 4 node cloud with ceph successfully. (Without the patch, it already failed to install the SP1 ceph nodes).

**Comment by rhafer** [comment]
The ci will need to be retriggered once a new D:C:7 build is there (with the lxml issue solved)

**Comment by rsalevsky** [comment]
@rhafer At this point we only have the SLE repos, so we need to wait for the new SLE iso.

**Comment by toabctl** [comment]
tested manually and works for me. +1

**Comment by s-t-e-v-e-n-k** [comment]
+1

**Pull request merged**
