### PR TITLE
Fix handling of manila service instance during upgrade

### PR DESCRIPTION
**Pull request by rhafer**
During the upgrade the manila service vm is shutdown. So when before
re-applying the manila barclamp check for the state of the manial-service
instance. If it exists and is in state "SHUTOFF" restart it. If it does not
exist boot a new instance. Otherwise assume it's running.

Additional fix: Set OS_TENANT_NAME to "manila-service" also if the Project
already exists.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by MaximilianMeister** [comment]
@rhafer thanks! I have triggered an upgrade gating (it was `all_noreboot`)

**Comment by rhafer** [comment]
That last gating failure was most probably fixed by: https://github.com/SUSE-Cloud/automation/commit/97e4090abb87047fb746cef148f90306ed7f6ce2

I'll retrigger an upgrade gating once the normal gating succeeded. As this PR also change non-upgrage related code paths.

**Comment by MaximilianMeister** [comment]
+1

**Pull request merged**
