### PR TITLE
Cloud 7 updates repo is needed when doing Cloud6->7 upgrade

### PR DESCRIPTION
**Pull request by jsuchome**
This was removed by https://github.com/SUSE-Cloud/automation/pull/1736

### CODE REVIEW

**Comment by rhafer** [comment]
@jsuchome Pardon my ignorance, but could you please clarify why this is needed? (preferably in the commit mesages)

**Comment by Itxaka** [comment]
doesnt seem like it was removed, but it changed for adding that repo to all cloud7 repos (develcloud7|susecloud7|M?|Beta*|RC*|GMC*) to only adding that repo if the cloudsource is GM7+up[0]

Shouldnt we use GM7+up as the `upgrade_cloudsource` instead of forcing the add of the repos?

:-1: from me

[0] https://github.com/SUSE-Cloud/automation/pull/1736/files#diff-c202af9895fd7be9224b15a93a00b0ffR945

**Comment by vmoravec** [comment]
@Itxaka It will not work as we might need recent not-yet-released patches for tests in SOC7 , and those are only in develcloud7.

**Comment by jsuchome** [comment]
If `GM7+up` is delivering the same packages for use as `develcloud7`, i would be fine with that. 

But I'm afraid that's not true, with `develcloud7` we get Cloud iso from Staging which is where our current patches to master go automatically, before official approval as maintanance updates. I think.

**Comment by Itxaka** [comment]
@jsuchome @vmoravec ahh, indeed :(

**Pull request merged**
