### PR TITLE
keystone: Ony test update_keystone_password for Cloud 7+

### PR DESCRIPTION
**Pull request by rsalevsky**
Commit e0c50fda50413f910cd7ccdb885923a3e480dd46 broke the Cloud 6 CI
jobs.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
so does SOC6 not have a way to update keystone passwords?

**Comment by rsalevsky** [comment]
@bmwiedemann Not via the keystone proposal.

**Comment by bmwiedemann** [comment]
But I did that for our cloud.suse.de SOC6 deployment via
https://github.com/SUSE-Cloud/automation/blob/production/scripts/productioncloud/batch-users.yaml

**Comment by rsalevsky** [comment]
@bmwiedemann I doubt that you use the `updated_password` password key in keystone as it doesn't exist in Cloud 6. Maybe there are other ways but this doesn't matter for this PR as it only fixes a new regression for Cloud 6 an alternative would be to revert the complete PR which broke it.

**Pull request merged**
