### PR TITLE
only trigger builds of our own PRs

### PR DESCRIPTION
**Pull request by jdsn**
no not trigger automatic builds of anybodys PR for obvious reason

### CODE REVIEW

**Comment by aspiers** [comment]
LGTM - can you test by submitting a PR via another user who is not in either team?

**Comment by jdsn** [comment]
@aspiers I already did, I removed @aplanas from the team (just for a few minutes) and his PRs disappeared.

**Comment by aspiers** [comment]
Excellent, +1 from me then!

**Comment by bmwiedemann** [comment]
:+1: though the .head is still confusing, as if different commits of the PR could come out of different source repos

**Pull request merged**
