### PR TITLE
Fix vnc_keymap in scenario files

### PR DESCRIPTION
**Pull request by vmoravec**
Wrong value "de-de" is replaced with correct one "de".

### CODE REVIEW

**Comment by jsuchome** [comment]
Do you have any reference that the change is correct? And don't we use 'de-de' as default value in nova recipe? That would need a fix.

**Comment by vmoravec** [comment]
@jsuchome The default is `en-US` as stated in http://docserv.nue.suse.com/documents/Cloud6/suse-openstack-cloud-deployment/single-html/#sec.depl.trouble.faq.misc.keymap

I have tested the "de" value, it works, other options like "de-de", "de_DE" or "de-DE" do not.

**Comment by vmoravec** [comment]
The error I got was actually `No valid host was found. There are not enough hosts available`, not very helpful, but @mjura helped me to dig the real cause of the problem.

**Comment by jsuchome** [comment]
So `en-US` is correct and works, right?

+1 for that `de-de` -> `de` change

**Comment by vmoravec** [comment]
@jsuchome hm, good point, I tested `en-US` and it also doesn't work :)

**Pull request merged**
