### PR TITLE
upgrade: Initialize correct value for the progress file.

### PR DESCRIPTION
**Pull request by jsuchome**
Base it on the initial value of $cloudsource.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
I'd prefer to keep the code in qa_crowbarsetup to be also used for non-virtual clouds. Any reason for the move?

**Comment by jsuchome** [comment]
@bmwiedemann that was my original idea, but then I do not exactly know how to set it in qa_crowbarsetup only for the first time - so it is not changed to "8-9" once later steps from `crowbarupgrade_5plus` are executed (after global change of `$cloudsource`)

**Comment by rhafer** [comment]
@jsuchome Hm, do we really need to have the version numbers in the progress file? Does anything in crowbar really rely on that? Or was it just done that way to be able to keep the progress files accross multiple version upgrades?

**Comment by jsuchome** [comment]
@rhafer good point. Currently crowbar checks the specific (versioned) file at several places but maybe it is unnecessary.

We could avoid stuff like https://github.com/crowbar/crowbar-core/pull/1444 ... however that might become complicated if the upgrade process were different in 7-8 (see `upgrade_steps_7_8`)

**Comment by rhafer** [comment]
Ideally it would put the version info into the file, instead of abuse the filename for but. But I have absolutely no idea how much changes would be required for that.

**Comment by skazi0** [comment]
@rhafer the version was not always in the filename. the idea came from here: https://trello.com/c/MZP6krgU/117-3-restrict-api-access-during-upgrade .
IIRC the problem was that we used a simple "file exists" check to filter all API requests. If the version was inside the file, it would need to be parsed on every request just to check the version. It can be quite big when some error or status messages are included. Not to mention locking.

**Comment by jsuchome** [comment]
@skazi0 you have quite a memory! ;-)

**Comment by skazi0** [comment]
@jsuchome persisted on github.com and trello.com :D:D

**Comment by rhafer** [comment]
>  the idea came from here: https://trello.com/c/MZP6krgU/117-3-restrict-api-access-during-upgrade .

Thanks for digging that one out! :)

> IIRC the problem was that we used a simple "file exists" check to filter all API requests. If the version was inside the file, it would need to be parsed on every request just to check the version.  It can be quite big when some error or status messages are included. Not to mention locking.

True. Though that doesn't quite explain why that file needs to contain the version numbers. Do we need to keep that file after a successful upgrade? I supposed we could also just remove it. Or rename it if we needed to keep track of previous upgrades.

In the end I am fine with this PR. I am just thinking about possible solutions to the issue @bmwiedemann  raised.

**Comment by skazi0** [comment]
@rhafer I wish we had documented all of those small corner cases which made it look like this... We can't delete the file after upgrade as it will cause `crowbarctl upgrade status` command to fail (or return empty result). It's not unlikely that the user will be interested in the upgrade status also after upgrade is over. With the status file left after upgrade, we need to take care of it when starting 7-8 upgrade (if both files are there, crowbarctl should use the newer one one) and/or maybe delete the old one.
PS. at some point we considered removing the file and using it as "upgrade ongoing" indicator but eventually we created another "running" file just for that to not hit some of the mentioned "after-problems".

**Comment by rhafer** [comment]
@skazi0 Thanks for all the details. Given all that I guess the most reasonable way currently really is this PR.

**Pull request merged**
