### PR TITLE
Add develcloud6 to the help text

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
one entry still missing in the sanity checks

**Comment by rsalevsky** [comment]
done

**Comment by MaximilianMeister** [comment]
:+1:

**Comment by bmwiedemann** [comment]
then we might as well drop develcloud3 + GM3 and add GM5

**Comment by rsalevsky** [comment]
As far as I know cloud3 is not EOL yet.

**Comment by thutterer** [comment]
+1

**Pull request merged**
