### PR TITLE
Use SLE12 SP1 SDK for installing ruby2.1/bundler

### PR DESCRIPTION
**Pull request by dirkmueller**
cct needs bundler-deps installed, which we can get from SDK.

### CODE REVIEW

**Comment by aspiers** [comment]
Would be nice if it explained why this is required now when it wasn't before.  But +1 if it fixes gating, even though I don't understand it.

**Comment by dirkmueller** [comment]
@aspiers I removed some "overlays" of packages from Shared:Rubygem that we should be picking from the officialproduct instead, which caused the regression (because suddenly packages are not available anymore that were available previously accidentally).

**Comment by bmwiedemann** [comment]
:+1: test passed and change looks Ok.

**Comment by aspiers** [comment]
@dirkmueller Thanks.  +0.5, or +1 if you update the commit message to explain this :)

**Pull request merged**
