### PR TITLE
qa_openstack: Adjust VG setup

### PR DESCRIPTION
**Pull request by toabctl**
Let openstack-loopback-lvm from openstack-quickstart do the
LVM volume group setup.

### CODE REVIEW

**Comment by toabctl** [comment]
Depends on  https://github.com/SUSE-Cloud/openstack-quickstart/pull/56

**Comment by jgrassler** [comment]
+1

**Comment by dirkmueller** [comment]
not sure I get that... why not create two volume groups on dev/vdb  and just add vdc as an extra pv to the vg if it exists?

**Comment by toabctl** [comment]
> not sure I get that... why not create two volume groups on dev/vdb and just add vdc as an extra pv to the vg if it exists?

@dirkmueller I think you can't create multiple VGs on a single PV. Can you?

**Comment by toabctl** [comment]
accidentally closed. pardon.

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
