### PR TITLE
Switch to cinderclient instead of using nova volume

### PR DESCRIPTION
**Pull request by dirkmueller**
Nova volume is deprecated at least since Grizzly, and
meanwhile it spits out deprecation warnings.

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by toabctl** [comment]
@jdsn @bmwiedemann any +/-1 ?

**Comment by aplanas** [comment]
+1

**Comment by bmwiedemann** [comment]
looks OK. test for cloud6 passed. re-triggered with cloud4 and if that passes, it is a +1 from me.

**Pull request merged**
