### PR TITLE
use json route to avoid redirection

### PR DESCRIPTION
**Pull request by MaximilianMeister**
depends on ~~https://github.com/crowbar/crowbar-core/pull/428~~ https://github.com/crowbar/crowbar-core/pull/420

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by jdsn** [comment]
:+1:

**Comment by jdsn** [comment]
btw. does this change work for Cloud 5 and 6?

**Comment by MaximilianMeister** [comment]
> btw. does this change work for Cloud 5 and 6?

good point, not yet but I will make a backport once https://github.com/crowbar/crowbar-core/pull/428 is merged.

**Comment by MaximilianMeister** [comment]
@jdsn Cloud 6 backport can be found at https://github.com/crowbar/crowbar-core/pull/420
and regarding cloud 5 there are no changes needed, as we don't have the start action in the `upgrades_controller`

**Comment by MaximilianMeister** [comment]
I think we can merge this now, as the json endpoint is now available in crowbar. the last commit after your +1's was a rebase

**Comment by jdsn** [comment]
merging now, gating failure was in reapplying manila proposal (unrelated to this change)

**Pull request merged**
