### PR TITLE
Avoid node update races on allocation

### PR DESCRIPTION
**Pull request by dirkmueller**
Horrible workaround for crowbar bug. Crowbar first sets
the node state to "discovered", and then goes through and
calls the transition hooks over all barclamps, which can take
quite a while. However, if we move forward already we're causing
tons of stress on crowbar with the node rename, and then it will
just run into races. Actual fix would be to only change the
state once the state is actually changed. (d'oh!)

### CODE REVIEW

**Comment by vmoravec** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by bmwiedemann** [comment]
IMHO, crowbar should be able to handle stress... it is OK to respond slower, but it should not fail.

**Comment by vuntz** [comment]
> IMHO, crowbar should be able to handle stress...

As said in the commit message, it's a workaround...

**Pull request merged**
