### PR TITLE
qa_crowbarsetup: import PTF key

### PR DESCRIPTION
**Pull request by bmwiedemann**
on admin server, if available
(only when run after crowbar is setup)

### CODE REVIEW

**Comment by gonzolino** [comment]
Tested the patch in our lab and it works nicely.
Also, the solution is much more elegant than my solution in https://github.com/sap-oc/automation/commit/e886c7df15393e1a07787b376c61d39048a64928

**Comment by bmwiedemann** [comment]
@dirkmueller --auto-import-keys will import any new keys, thus weakening security

and in general we could do it in the product as well, since we create the key there already, we could also tell rpm to trust it. Just might need some time for the updates to go through the pipeline

**Comment by dirkmueller** [comment]
@bmwiedemann the installer already has code to create the ptf key, so there it should be marked as trusted.. https://github.com/crowbar/crowbar/blob/master/scripts/install-chef-suse.sh#L478

**Comment by bmwiedemann** [comment]
proposing https://github.com/crowbar/crowbar/pull/2320 to fix it properly in the product

**Comment by jdsn** [comment]
@bmwiedemann @rsalevsky do we need this workaround to be merged until the proposed fix ends up in the product everywhere?

**Pull request merged**
