### PR TITLE
qa_crowbarsetup: fix milestone regexp

### PR DESCRIPTION
**Pull request by bmwiedemann**
in order to not match M11 etc

### CODE REVIEW

**Comment by jdsn** [comment]
:+1:

**Comment by vuntz** [comment]
+11

**Comment by mjura** [comment]
I propose to use ^M[1-6]{1}$

**Comment by jdsn** [comment]
> I propose to use ^M[1-6]{1}$

To be on the very safe side it should be:
`I propose to use ^M[1-6]{1,1}$`

:)

**Comment by bmwiedemann** [comment]
@mjura nay, simpler is better according to William of Ockham

**Pull request merged**
