### PR TITLE
jenkins: Enforce postgresql as a database in HA

### PR DESCRIPTION
**Pull request by rsalevsky**
The idea is to switch the database default to mariadb but this is not
yet working for HA.

### CODE REVIEW

**Comment by jsuchome** [comment]
This does not make sense IMHO. We just switch to mysql backend once it is working.

**Comment by rsalevsky** [comment]
@jsuchome For non-HA builds we assume it works but we only test it in one scenario so we can't be sure unless we give it more testing. Additional we start giving it to customers so we should also start using our own dog food. So IMHO it doesn't make sense to wait any longer.

**Comment by jsuchome** [comment]
I actually think we could go and allow it for HA jobs as well. We currently have one card that targets the problem during HA deployment: https://trello.com/c/owkJsTKy/35-node-fenced-after-the-failed-haproxy-restart

**Comment by jsuchome** [comment]
See? It's not that bad: https://ci.suse.de/view/Cloud/view/Cloud7/job/cloud-mkcloud7-job-ha-mariadb-x86_64/

**Pull request merged**
