### PR TITLE
With mixed SP1 and SP2 setup, use SP2 compute nodes

### PR DESCRIPTION
**Pull request by jsuchome**
This should prevent failures like this one: https://ci.suse.de/job/openstack-mkcloud/30594/console

### CODE REVIEW

**Comment by nicolasbock** [comment]
Looks like gating is still failing with the same issue?

**Comment by jsuchome** [comment]
Note that I called gating job for this PR with want_sles12sp2=1

**Comment by jsuchome** [comment]
@nicolasbock you mean usual SP1 based gating? That's possible; if that is true than it is likely caused by new libvirt packages in PTF repo

**Comment by nicolasbock** [comment]
@jsuchome It's cleared now. You were right about the libvirt package.

+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
