### PR TITLE
Create more instances that should survive the upgrade

### PR DESCRIPTION
**Pull request by jsuchome**
This is just a test so far. Obviously it should be parametrized somehow ... both qa_crowbarsetup and the heat template... @abel-navarro maybe you have some good idea as you've started with the original heat solution?

### CODE REVIEW

**Comment by abel-navarro** [comment]
Although this proposal is correct I would rather make the number of instances configurable, otherwise there's lots of boilerplate. The solution I proposed some time ago (https://github.com/SUSE-Cloud/automation/pull/1580) did already give you that option. In that solution there was not the concept of east-west or north-south traffic.

The north-south part is easy. Just pass an outside IP as done in this PR or even hard code it. The east-west part looks a bit more complicated.

It shouldn't be hard to adapt the template to always have two VMs per network (east-west) and then use the ping between them.

I tried to look a solution for daisy chaining the pings (VM(n+1) to VM(n)) but doesn't look easy to implement with heat, so my other proposal should be better.

**Comment by jsuchome** [comment]
Yes, I know it should be configurable, I just do not want to spend more time with it ;-)

**Comment by jsuchome** [comment]
> abel-navarro approved these changes a minute ago

I actually **want** to make it configurable and I'm against merging myself :-)

**Comment by jdsn** [comment]
@jsuchome @abel-navarro 
- no news since months
- needs rebase
- do-not-merge-yet label

Is this PR still needed and will you update it or can we close it?

**Comment by jsuchome** [comment]
We can close it I think

**Pull request closed without merging**
