### PR TITLE
Upgrade fixup

### PR DESCRIPTION
**Pull request by MaximilianMeister**
some minor enancements for https://github.com/SUSE-Cloud/automation/pull/1156

### CODE REVIEW

**Comment by jsuchome** [comment]
+1

**Comment by nicolasbock** [comment]
+1

**Comment by bmwiedemann** [comment]
test failed with
```
Error: Waiting for 'crowbar init service to start' timed out.
```

**Comment by jdsn** [comment]
:+1:

**Comment by jdsn** [comment]
-100  after redoing PR #1105 it now obsoletes this PR (the cleanup idea is already included there)

**Comment by MaximilianMeister** [comment]
> -100 after redoing PR #1105 it now obsoletes this PR (the cleanup idea is already included there)

cool that you continued on this. but you didn't fix all things there, so I let the 2 commits as they are, and just removed the commits that you've taken care of in #1105

**Comment by jdsn** [comment]
ok, then I am +1 for this, if we can make the gating pass

**Pull request merged**
