### PR TITLE
mkcloud: complain only once per line

### PR DESCRIPTION
**Pull request by MaximilianMeister**
otherwise there would be an `Error:` for every line

### CODE REVIEW

**Comment by aspiers** [comment]
I don't understand, why would there be an `Error:` for every line?

**Comment by MaximilianMeister** [comment]
@aspiers the outpput would look like 
```bash
Error: This script needs to be run as root
Error: Please be aware that this script will create a LVM
Error: and kill all current VMs on this host.
```

**Comment by aspiers** [comment]
OK that's a weird feature of `printf(1)` which I didn't know about.  BTW personally I think I prefer that style of output, but I don't really care too much either way.

**Comment by aspiers** [comment]
Hmm, looking at this more closely - doesn't it result in a massive indent for the subsequent lines, the size of which depends on how far that particular code block is indented?  And that doesn't make sense.

**Comment by aspiers** [comment]
http://unix.stackexchange.com/questions/76481/cant-indent-heredoc-to-match-nestings-indent

**Pull request merged**
