### PR TITLE
Fix s390x again

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by rhafer** [comment]
Nitpick: The commit message of 030beddf9aa is misleading. You're setting autodeflate=on for everything not just s390.

Other than that this seems fine.

**Comment by dirkmueller** [comment]
@rhafer done

**Comment by rhafer** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by Itxaka** [comment]
+1

**Pull request merged**
