### PR TITLE
Add public key for zzaimeche

### PR DESCRIPTION
**Pull request by zzaimeche**

### CODE REVIEW

**Comment by toabctl** [comment]
needs a rebase

**Comment by JanZerebecki** [comment]
You are neither in the SUSE nor SUSE-Cloud github group, should that be fixed?

**Comment by zzaimeche** [comment]
That should have been fixed now.

________________________________

**Comment by JanZerebecki** [comment]
You are still not in SUSE-Cloud. Still or again needs a rebase.

**Pull request closed without merging**
