### PR TITLE
qa_crowbarsetup: Generate SSL certificate for Horizon

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by vuntz** [comment]
Should fix https://ci.suse.de/job/cloud-mkcloud6-scenario-ha-ssl/5/

**Comment by bmwiedemann** [comment]
:+1:

**Comment by aplanas** [comment]
+1

**Comment by bmwiedemann** [comment]
https://ci.suse.de/view/Cloud/view/Builds/job/openstack-mkcloud/14682/ is looking good - it is a re-run of a run that previously failed in applying horizon

**Pull request merged**
