### PR TITLE
Replace glance with openstack client

### PR DESCRIPTION
**Pull request by mjura**
This task was defined in 

https://trello.com/c/qg2oVp3W/400-3-p5-bnc-932270-image-creating-stuck-at-queued-when-using-ceph-and-openstack-client-command

### CODE REVIEW

**Comment by bmwiedemann** [comment]
needs testing with develcloud4

**Comment by mjura** [comment]
> needs testing with develcloud4

It was tested also with develcloud4

**Comment by rsalevsky** [comment]
:+1:

**Comment by bmwiedemann** [comment]
:+1:

**Comment by jdsn** [comment]
:+1:

**Pull request merged**
