### PR TITLE
clouddata must also be a fqdn

### PR DESCRIPTION
**Pull request by tpatzig**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
we have `$clouddatadns` for those places where we want a FQDN.
if $clouddata is not an IP-addr, the NFS mounts on the admin node will be gone after a reboot, because the named deps say, it depends on nfs-client, while it is the other way here.

**Comment by aplanas** [comment]
why not to use a single variable that can contain IP or FQDN and use `getent hosts` to the the missing part?

```
$ getent hosts clouddata.cloud.suse.de
10.162.191.194  clouddata.cloud.suse.de

$ getent hosts 10.162.191.194
10.162.191.194  clouddata.cloud.suse.de
```

**Comment by jdsn** [comment]
+1 for @aplanas 

I would prefer one single variable that I have to to set (hostname or IP, whatever I desire), and mkcloud will compute the missing parts as needed.
I would even propose that the variable that gets set from the user is never used in mkcloud, and the variables that mkcloud uses for clouddata{dns,ip} can not be set from outside.
This should be damn easy to use and solid as mkcloud does the sanity checks and comutes the stuff it needs internally.

**Comment by tpatzig** [comment]
@bmwiedemann for nfs mounts we added clouddata_nfs

**Comment by jdsn** [comment]
> for nfs mounts we added clouddata_nfs

another reason to do a clean up here :)

`$clouddata` was meant to hold an IP address and `$clouddatadns` was meant to hold the FQDN.
So `$clouddata_nfs` seems to be obsolete and `$clouddata` should have been used instead.

Anyway: I still think that we should only have one variable to set from outside and mkcloud should compute the rest that it needs.

**Comment by tpatzig** [comment]
this will not work for us. clouddata points to our reposerver, where we mirror the suse repos to (same as smturl), where we store images and sync our obs repos to. But this is not an nfs server.
We have setup a nfs server, to fulfill mkcloud requirements, on the mkcloud HV. I think it must be possible to have different settings for http and nfs source services.

**Comment by jdsn** [comment]
> this will not work for us. clouddata points to our reposerver, where we mirror the suse repos to (same as smturl), where we store images and sync our obs repos to. But this is not an nfs server.

Ok, then the use of `$clouddata` in this context is wrong :)
`clouddata` for us is one and the same machine.
So in this case I guess we should split this by service. Then I would propose (to really make it clear what happens):
- we drop all `$clouddata*` variables
- we introduce something like `$reposerver` and `$nfsserver` (names to be refined)
- for backward compatibility we set the new variables to the value of `$clouddata`, but we only use the new ones in code
- you stop to use `$clouddata` at all and only set the new vars

**Comment by aspiers** [comment]
@jdsn Big +1 for this proposal. Host variable naming according to functionality is much nicer than naming based on some hardcoded hostname only available internally within SUSE.

**Comment by tpatzig** [comment]
Having this variables seperated per usage would be fine for use. 
So we would have: reposerver, nfsserver, smtserver. What about $susedownload (or this looks more like a $obsdownload)?

**Comment by jdsn** [comment]
btw. I am working on a PR according to my proposal, so IMHO we can close this PR

**Comment by jdsn** [comment]
Superseeded by https://github.com/SUSE-Cloud/automation/pull/1933
Thus closing this PR.

**Pull request closed without merging**
