### PR TITLE
Add nova shared_instance_storage support

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
we should document those options somewhere.
[nova_with_ssl](https://github.com/SUSE-Cloud/automation/blob/master/scripts/mkcloud#L321) and maybe more options are also not documented anywhere, not even in the undocumented options.
opened https://github.com/SUSE-Cloud/automation/issues/256

but codewise :+1: as it has been done like this for `nova_with_ssl` as well

**Comment by aspiers** [comment]
> we should document those options somewhere.

Right.  A good rule of thumb is: no PR should **ever** increase the amount of technical debt.  So please do not ever add new options without adding the corresponding documentation.  If the new options are similar to already existing options which are missing documentation, then that is not an excuse to skip documenting the new options; rather it is a good opportunity to add documentation for the existing options alongside the new documentation for the new options :)  

So personally I would have said -1, but thanks to Max for submitting #256 so we can at least ensure this gets fixed later.

**Comment by dguitarbite** [comment]
I did not see a -1 from Max, so I assumed that its more of a general suggestion than a no go for this patch. I support documenting the features. Thanks for creating #256.

**Comment by rsalevsky** [comment]
I discussed this with Max yesterday, the point is we have no suitable documentation for the options. There is only a pull request #228 which introduce them.

**Comment by MaximilianMeister** [comment]
> There is only a pull request #228 which introduce the documentation.
 not for those undocumented options, I just took the documentation we already have

**Pull request merged**
