### PR TITLE
Assign magnum-server role to HA cluster for hacloud=1.

### PR DESCRIPTION
**Pull request by jgrassler**
This pull request enables HA for the Magnum barclamp. Merge once https://github.com/crowbar/crowbar-openstack/pull/511 is merged.

### CODE REVIEW

**Comment by toabctl** [comment]
Shouldn't that be done automatically? I think we don't have similar code for other services...

**Comment by jgrassler** [comment]
No, it needs a nudge from mkcloud (and/or whoever sets up the cloud manually). At least we have that sort of code for other services' roles as well:

https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L2852
https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L2864
https://github.com/SUSE-Cloud/automation/blob/master/scripts/qa_crowbarsetup.sh#L2927

**Comment by jgrassler** [comment]
I think this can in fact be merged before : I did what this pull request does manually (assign the `data` cluster of an HA cloud to a the `magnum-server`) to a Magnum barclamp that was missing the HA enabling bits of https://github.com/jgrassler/crowbar-openstack/blob/magnum-ha/crowbar_framework/app/models/magnum_service.rb#L114 because I hadn't restarted Crowbar. All I got was a non-HA magnum deployment which was superseded by a HA enabled one after a Crowbar restart.

So I recommend we merge this first, so HA gating can function for https://github.com/crowbar/crowbar-openstack/pull/511.

**Comment by vuntz** [comment]
+1

**Comment by toabctl** [comment]
+1

**Pull request merged**
