### PR TITLE
Wait for powerdown

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by nkrinner** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by dirkmueller** [comment]
(Note, still need to test this change more thoroughly)

**Comment by bmwiedemann** [comment]
test failed on DC5 want_sles12=1 :
onadmin_rebootcloud
Warning: Permanently added '192.168.225.10' (ECDSA) to the list of known hosts.
Waiting for: node d52-54-01-77-77-01.g15.cloud.suse.de to go down
.......................
Waiting for: unknown process
....................................................................................................
Error: Waiting for 'unknown process' timed out.
This check was used: crowbar node_state status | grep d52-54-01-77-77-01.g15.cloud.suse.de | grep -q 'Power'
+ return 11

which is probably the bug that is tested for...

**Comment by dirkmueller** [comment]
@bmwiedemann yeah, it hangs for 2 minutes on shutdown due to the cinder/tgt changes .. I've extended the timeout.

**Comment by rsalevsky** [comment]
@bmwiedemann Can trigger the test again pls?

**Pull request merged**
