### PR TITLE
Remove nfs setup for mariadb database

### PR DESCRIPTION
**Pull request by gosipyan**
Update CI job configuration

### CODE REVIEW

**Comment by gosipyan** [comment]
[P6 (5) Test HA failover for MariaDB](https://trello.com/c/bMtK40jZ/3-p6-5-test-ha-failover-for-mariadb)

**Comment by vmoravec** [comment]
Is the current state still WIP?

**Comment by gosipyan** [comment]
@vmoravec  No sorry ,I wanted change job in that way not to add completely new one but not sure if it good idea.

**Comment by vmoravec** [comment]
If it makes sense for you to have it that way during the testing before mariadb gets merged into crowbar master, why not. We can remove the scenario file once we are that far.  

But I would add a comment to the parameter description that the scenario 1c must be added manually before triggering the job, otherwise the scenario 1a using postgres as db engine will be used.

**Pull request merged**
