### PR TITLE
Move host specifc config files out of scripts/

### PR DESCRIPTION
**Pull request by dirkmueller**
This further reduces footprint of scripts/, which is now installed on all mkcloud hosts

### CODE REVIEW

**Comment by bmwiedemann** [comment]
This moves some scripts into the config dir - better to use a hostscripts dir or such for those.

**Comment by jdsn** [comment]
@dirkmueller @bmwiedemann 
As it might be harder to move everything out of scripts (while keeping in mind that `scripts` means `mkcloud_scripts`, it may be easier collect all mkcloud related tools in something like `/scripts/mkcloud/`. That would require another round of tooling change, but we could keep all other scripts within `/scripts/`.

But scenarios should still move out of scripts :)

Your thoughts?

**Comment by dirkmueller** [comment]
@jdsn @bmwiedemann changed to hostscripts/ and left out scenarios for now

**Comment by jdsn** [comment]
@dirkmueller The commit "Clean up wanttempest" seems to be unrelated to this PR, was it cherry-picked accidentally?

**Comment by jdsn** [comment]
This PR has the potential to break a lot. So we need to watch the jobs carefully to be able to fix it quickly.
Ideally changes to the jobs that use the scripts that you move here, should be change within this PR as well.

**Comment by jdsn** [comment]
withholding my approval for an answer to the above

**Comment by dirkmueller** [comment]
@jdsn as far as I know all the files I moved will not be referenced by any running jenkins jobs, they're merely backups of the actual copy on the servers. 

I can move the tempest cleanup to some other PR if you prefer.

**Comment by jdsn** [comment]
> ... they're merely backups of the actual copy on the servers

Unfortunately this is correct. I'll add a card to clean that up.

**Pull request merged**
