### PR TITLE
Add QAM test scenarios that to our jenkins

### PR DESCRIPTION
**Pull request by dirkmueller**
The QAM team is struggling to setup and pass the tests in
these configurations, so lets see if the issue is reproducible
in our CI system somehow.

### CODE REVIEW

**Comment by nicolasbock** [comment]
Is this scenario intended for debugging the QAM issue or will it be useful longer term?

**Comment by dirkmueller** [comment]
well, I'd keep it around I'd say

**Comment by rsalevsky** [comment]
We discussed in today's meeting a slightly different approach, so let's wait with this till the QAM team comes up with their final idea.

**Comment by jdsn** [comment]
@dirkmueller The job that is defined in this PR is already deployed on ci.suse.de.
Will it be removed soon and can we close this PC?
Or shall we rather merge this PR to get a consistent state?

**Comment by jdsn** [comment]
This job is already deployed and still identical to this job definition.
Merging it now in order to maintain it in git from now.

**Pull request merged**
