### PR TITLE
ardana: Set ANSIBLE_DEBUG

### PR DESCRIPTION
**Pull request by toabctl**
To get also debugging output where 'no_log' is set, the env var
ANSIBLE_DEBUG needs to be set[1].

[1]
http://docs.ansible.com/ansible/latest/faq.html#how-do-i-keep-secret-data-in-my-playbook

### CODE REVIEW

**Comment by toabctl** [comment]
But from http://docs.ansible.com/ansible/2.4/config.html#default-debug , it seems ```very``` verbose. I guess we should try it?

**Comment by cmurphy** [comment]
I'm not sure but I don't think this will help for the actual site.yml run which is where the no_log options are defined, I think you'd have to define this in that task in init.yml.

**Comment by toabctl** [comment]
> can you give details of exactly what difference I should expect to see?

@aspiers I thought I read that ```ANSIBLE_DEBUG``` will sort of remove the ```no_log``` parameter so you would see the output for tasks that have ```no_log``` . But I never tested it

**Comment by toabctl** [comment]
> I believe this needs to be set on the env where you run ansible, its not automatically forwarded to the other nodes (e.g. the deployer node where you run site.yml)

@dirkmueller Done

**Comment by toabctl** [comment]
> IIUC ANSIBLE_DEBUG is intended for debugging Ansible itself. When I tried it, it spewed massive amounts of info about Ansible internals which we don't care about.

Thanks adam for testing it. Looks like we don't want this.

**Pull request closed without merging**
